// data-source-seeder.ts -- Populates the data_sources table with provenance
// information for food and herb data.
//
// Tracks where each entity's properties came from (USDA, Ayurvedic texts,
// TCM references, manual entries) with confidence scores and validation dates.

import type { DbClient } from '../client.js';
import { dataSources } from '../schema/index.js';
import type { NewDataSource } from '../types.js';

// -------------------------------------------------------------------------
// Source registry
// -------------------------------------------------------------------------

export interface DataSourceDef {
  source_name: string;
  source_url: string | null;
  source_version: string | null;
  description: string;
}

/** Known data sources with provenance URLs. */
export const DATA_SOURCE_REGISTRY: DataSourceDef[] = [
  {
    source_name: 'USDA FoodData Central',
    source_url: 'https://fdc.nal.usda.gov',
    source_version: 'SR Legacy / Foundation 2024',
    description: 'US Department of Agriculture nutrient composition database',
  },
  {
    source_name: 'Ashtanga Hridayam',
    source_url: null,
    source_version: 'Sutrasthana, Ch. 6-8',
    description: 'Classical Ayurvedic text by Vagbhata on food properties and therapeutics',
  },
  {
    source_name: 'Charaka Samhita',
    source_url: null,
    source_version: 'Sutrasthana, Ch. 27',
    description: 'Foundational Ayurvedic text on food classification and dietary therapy',
  },
  {
    source_name: 'Bhavaprakasha Nighantu',
    source_url: null,
    source_version: 'Dhanya Varga, Phala Varga',
    description: 'Medieval Ayurvedic pharmacopoeia with food and herb classifications',
  },
  {
    source_name: 'Chinese Dietary Therapy (Liu)',
    source_url: null,
    source_version: '2nd Edition',
    description:
      'TCM food therapy reference by Liu Jilin and Peck, comprehensive food classification',
  },
  {
    source_name: 'Healing with Whole Foods (Pitchford)',
    source_url: null,
    source_version: '3rd Edition, 2002',
    description: 'Paul Pitchford reference integrating TCM, Ayurveda, and Western nutrition',
  },
  {
    source_name: 'WHO Monographs on Medicinal Plants',
    source_url: 'https://www.who.int/publications',
    source_version: 'Volumes 1-4',
    description: 'World Health Organization monographs on selected medicinal plants',
  },
  {
    source_name: 'EFSA Scientific Opinions',
    source_url: 'https://www.efsa.europa.eu',
    source_version: null,
    description: 'European Food Safety Authority scientific opinions on health claims',
  },
  {
    source_name: 'Indian Materia Medica (Nadkarni)',
    source_url: null,
    source_version: 'Revised Edition',
    description: 'Comprehensive reference on Indian medicinal plants and foods',
  },
  {
    source_name: 'Bensky Chinese Herbal Medicine',
    source_url: null,
    source_version: '3rd Edition, 2004',
    description: 'Dan Bensky reference on Chinese materia medica with herbal formulas',
  },
  {
    source_name: 'LLM-generated (Gemini 2.5)',
    source_url: null,
    source_version: null,
    description: 'Properties generated by Gemini 2.5 Flash, pending human review',
  },
  {
    source_name: 'LLM-generated (Claude)',
    source_url: null,
    source_version: null,
    description: 'Properties generated by Claude, pending human review',
  },
  {
    source_name: 'Manual entry',
    source_url: null,
    source_version: null,
    description: 'Manually entered by team members with cited sources',
  },
  {
    source_name: 'PubMed',
    source_url: 'https://pubmed.ncbi.nlm.nih.gov',
    source_version: null,
    description: 'Individual research papers from PubMed database',
  },
  {
    source_name: 'Examine.com',
    source_url: 'https://examine.com',
    source_version: null,
    description: 'Evidence-based nutrition and supplement research database',
  },
];

// -------------------------------------------------------------------------
// Canonical food source assignments
// -------------------------------------------------------------------------

export interface EntitySourceAssignment {
  entity_name: string;
  entity_type: 'food' | 'herb';
  sources: Array<{
    source_name: string;
    confidence_score: number;
    properties_covered: string[];
    validator: string;
    verification_date: string;
    disagreement_notes?: string;
  }>;
}

/**
 * Source provenance for canonical foods.
 * Each food maps to 1-3 sources covering different property groups.
 */
export const CANONICAL_SOURCE_ASSIGNMENTS: EntitySourceAssignment[] = [
  {
    entity_name: 'basmati rice',
    entity_type: 'food',
    sources: [
      {
        source_name: 'Ashtanga Hridayam',
        confidence_score: 0.95,
        properties_covered: ['rasa', 'virya', 'vipaka', 'guna', 'dosha_effects'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'Chinese Dietary Therapy (Liu)',
        confidence_score: 0.9,
        properties_covered: ['thermal_nature', 'flavor', 'organ_affinity', 'actions'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'USDA FoodData Central',
        confidence_score: 0.98,
        properties_covered: ['glycemic_index', 'bioactive_compounds'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
  {
    entity_name: 'oats',
    entity_type: 'food',
    sources: [
      {
        source_name: 'Healing with Whole Foods (Pitchford)',
        confidence_score: 0.85,
        properties_covered: [
          'rasa',
          'virya',
          'vipaka',
          'guna',
          'dosha_effects',
          'thermal_nature',
          'flavor',
        ],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'USDA FoodData Central',
        confidence_score: 0.98,
        properties_covered: ['glycemic_index', 'bioactive_compounds'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
  {
    entity_name: 'mung bean',
    entity_type: 'food',
    sources: [
      {
        source_name: 'Charaka Samhita',
        confidence_score: 0.95,
        properties_covered: ['rasa', 'virya', 'vipaka', 'guna', 'dosha_effects'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'Chinese Dietary Therapy (Liu)',
        confidence_score: 0.9,
        properties_covered: ['thermal_nature', 'flavor', 'organ_affinity', 'actions'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
  {
    entity_name: 'ghee',
    entity_type: 'food',
    sources: [
      {
        source_name: 'Ashtanga Hridayam',
        confidence_score: 0.98,
        properties_covered: ['rasa', 'virya', 'vipaka', 'guna', 'dosha_effects'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
        disagreement_notes:
          'TCM classifies ghee differently from butter; Ayurveda considers it sattvic',
      },
      {
        source_name: 'Charaka Samhita',
        confidence_score: 0.95,
        properties_covered: ['rasa', 'virya', 'vipaka', 'guna', 'dosha_effects'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
  {
    entity_name: 'spinach',
    entity_type: 'food',
    sources: [
      {
        source_name: 'USDA FoodData Central',
        confidence_score: 0.98,
        properties_covered: ['glycemic_index', 'bioactive_compounds'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'Chinese Dietary Therapy (Liu)',
        confidence_score: 0.9,
        properties_covered: ['thermal_nature', 'flavor', 'organ_affinity', 'actions'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
  {
    entity_name: 'turmeric',
    entity_type: 'food',
    sources: [
      {
        source_name: 'Bhavaprakasha Nighantu',
        confidence_score: 0.95,
        properties_covered: ['rasa', 'virya', 'vipaka', 'guna', 'dosha_effects', 'herb_actions'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'WHO Monographs on Medicinal Plants',
        confidence_score: 0.92,
        properties_covered: ['bioactive_compounds', 'contraindications', 'dosage_forms'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'Bensky Chinese Herbal Medicine',
        confidence_score: 0.9,
        properties_covered: ['thermal_nature', 'flavor', 'organ_affinity', 'actions'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
  {
    entity_name: 'ashwagandha',
    entity_type: 'herb',
    sources: [
      {
        source_name: 'Charaka Samhita',
        confidence_score: 0.95,
        properties_covered: ['rasa', 'virya', 'vipaka', 'guna', 'dosha_effects', 'herb_actions'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'Indian Materia Medica (Nadkarni)',
        confidence_score: 0.9,
        properties_covered: ['herb_actions', 'contraindications', 'dosage_forms'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
  {
    entity_name: 'ginger',
    entity_type: 'food',
    sources: [
      {
        source_name: 'Ashtanga Hridayam',
        confidence_score: 0.95,
        properties_covered: ['rasa', 'virya', 'vipaka', 'guna', 'dosha_effects'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'Bensky Chinese Herbal Medicine',
        confidence_score: 0.92,
        properties_covered: ['thermal_nature', 'flavor', 'organ_affinity', 'actions'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
      {
        source_name: 'WHO Monographs on Medicinal Plants',
        confidence_score: 0.9,
        properties_covered: ['bioactive_compounds', 'contraindications'],
        validator: 'canonical_v1',
        verification_date: '2026-04-01',
      },
    ],
  },
];

// -------------------------------------------------------------------------
// Seeder function
// -------------------------------------------------------------------------

/**
 * Seeds the data_sources table with provenance information for entities.
 *
 * @param db - Database client (service role).
 * @param entityIdLookup - Map of lowercase entity name to UUID (combined foods + herbs).
 * @returns Total number of data source rows inserted.
 */
export async function seedDataSources(
  db: DbClient,
  entityIdLookup: Map<string, string>,
): Promise<number> {
  const rows: NewDataSource[] = [];

  for (const assignment of CANONICAL_SOURCE_ASSIGNMENTS) {
    const entityId = entityIdLookup.get(assignment.entity_name.toLowerCase());
    if (!entityId) continue;

    for (const source of assignment.sources) {
      const registry = DATA_SOURCE_REGISTRY.find((r) => r.source_name === source.source_name);
      rows.push({
        entity_type: assignment.entity_type,
        entity_id: entityId,
        source_name: source.source_name,
        source_url: registry?.source_url ?? null,
        source_version: registry?.source_version ?? null,
        verification_date: source.verification_date,
        validator: source.validator,
        confidence_score: source.confidence_score.toFixed(2),
        disagreement_notes: source.disagreement_notes ?? null,
        properties_covered: source.properties_covered,
      });
    }
  }

  if (rows.length === 0) return 0;

  // Insert in chunks of 200 to avoid parameter limits
  const CHUNK_SIZE = 200;
  for (let i = 0; i < rows.length; i += CHUNK_SIZE) {
    const chunk = rows.slice(i, i + CHUNK_SIZE);
    await db.insert(dataSources).values(chunk);
  }

  return rows.length;
}
