// evidence-seeder.ts -- Populates the evidence_claims table with scientific
// evidence backing food health claims.
//
// Two sources of evidence claims:
// 1. Canonical foods: hardcoded claims from food-database-v1.md
// 2. Remaining foods: to be generated by LLM in a future step
//
// Uses a duplicate check on (food_id, claim) to prevent exact duplicates.
// Claims are append-only -- existing claims are not updated.

import { and, eq } from 'drizzle-orm';
import type { DbClient } from '../client.js';
import { evidenceClaims } from '../schema/index.js';
import type { NewEvidenceClaim } from '../types.js';

// -------------------------------------------------------------------------
// Evidence levels
// -------------------------------------------------------------------------

export const EVIDENCE_LEVELS = ['strong', 'moderate', 'emerging', 'traditional_only'] as const;

export type EvidenceLevel = (typeof EVIDENCE_LEVELS)[number];

// -------------------------------------------------------------------------
// Evidence claim data
// -------------------------------------------------------------------------

export interface EvidenceClaimEntry {
  food_name: string;
  claims: Array<{
    claim: string;
    evidence_level: EvidenceLevel;
    source_citation: string;
    pubmed_id?: string;
  }>;
}

/**
 * Curated evidence claims for canonical foods.
 * Derived from the Naturopathy sections of food-database-v1.md.
 */
export const CANONICAL_EVIDENCE_CLAIMS: EvidenceClaimEntry[] = [
  {
    food_name: 'basmati rice',
    claims: [
      {
        claim:
          'Basmati rice has a lower glycemic index (50-58) compared to other white rice varieties (70-80), resulting in slower blood glucose elevation',
        evidence_level: 'strong',
        source_citation: 'Kaur et al., J Food Sci Technol 2016',
        pubmed_id: '27570271',
      },
      {
        claim:
          'Amylose content in basmati (20-25%) creates more resistant starch during cooling, further lowering glycemic response',
        evidence_level: 'moderate',
        source_citation: 'Sonia et al., Nutr Res 2015',
      },
    ],
  },
  {
    food_name: 'oats',
    claims: [
      {
        claim:
          'Beta-glucan fiber in oats reduces LDL cholesterol by 5-10% when consumed at 3g/day or more',
        evidence_level: 'strong',
        source_citation: 'EFSA Panel, EFSA Journal 2011',
      },
      {
        claim:
          'Regular oat consumption improves insulin sensitivity and reduces fasting glucose in type 2 diabetes',
        evidence_level: 'strong',
        source_citation: 'Whitehead et al., Am J Clin Nutr 2014',
        pubmed_id: '25411276',
      },
      {
        claim:
          'Oat avenanthramides have anti-inflammatory and antioxidant properties comparable to some pharmaceutical agents',
        evidence_level: 'moderate',
        source_citation: 'Meydani, Nutr Rev 2009',
        pubmed_id: '19017329',
      },
    ],
  },
  {
    food_name: 'quinoa',
    claims: [
      {
        claim:
          'Quinoa provides all 9 essential amino acids with a protein quality comparable to casein (PDCAAS 0.87)',
        evidence_level: 'strong',
        source_citation: 'Abugoch, Adv Food Nutr Res 2009',
      },
      {
        claim:
          'Saponins in quinoa have demonstrated anti-inflammatory and anti-cancer properties in vitro',
        evidence_level: 'emerging',
        source_citation: 'Graf et al., Food Chem 2015',
        pubmed_id: '25306340',
      },
    ],
  },
  {
    food_name: 'mung bean',
    claims: [
      {
        claim:
          'Mung bean protein hydrolysates show ACE-inhibitory activity comparable to captopril, suggesting antihypertensive potential',
        evidence_level: 'emerging',
        source_citation: 'Li et al., J Food Sci 2006',
      },
      {
        claim:
          'Vitexin and isovitexin in mung beans have demonstrated antioxidant and anti-diabetic effects in animal models',
        evidence_level: 'emerging',
        source_citation: 'Yao et al., J Agric Food Chem 2014',
        pubmed_id: '24988476',
      },
    ],
  },
  {
    food_name: 'red lentil',
    claims: [
      {
        claim:
          'Replacing half of a high-GI starchy food with lentils reduces postprandial glucose by 20-35%',
        evidence_level: 'strong',
        source_citation: 'Sievenpiper et al., Diabetologia 2009',
        pubmed_id: '19396425',
      },
      {
        claim:
          'Regular lentil consumption (3+ servings/week) is associated with 22% lower risk of cardiovascular events',
        evidence_level: 'moderate',
        source_citation: 'Afshin et al., Am J Clin Nutr 2014',
      },
    ],
  },
  {
    food_name: 'chickpea',
    claims: [
      {
        claim:
          'Chickpea consumption improves glycemic control with HbA1c reduction of 0.3% in diabetic subjects over 12 weeks',
        evidence_level: 'moderate',
        source_citation: 'Pittaway et al., J Am Coll Nutr 2008',
        pubmed_id: '18460479',
      },
      {
        claim:
          'Resistant starch in chickpeas (4-5g per 100g cooked) promotes beneficial gut microbiota and short-chain fatty acid production',
        evidence_level: 'moderate',
        source_citation: 'Fernando et al., Crit Rev Food Sci Nutr 2010',
      },
    ],
  },
  {
    food_name: 'spinach',
    claims: [
      {
        claim:
          'Spinach thylakoid supplements reduce hunger by 95% and ghrelin response by 25% in clinical trials',
        evidence_level: 'moderate',
        source_citation: 'Stenblom et al., Appetite 2015',
        pubmed_id: '25449840',
      },
      {
        claim:
          'Lutein and zeaxanthin in spinach reduce age-related macular degeneration risk by 26% at high dietary intake',
        evidence_level: 'strong',
        source_citation: 'AREDS2 Research Group, JAMA Ophthalmol 2014',
        pubmed_id: '24604849',
      },
    ],
  },
  {
    food_name: 'sweet potato',
    claims: [
      {
        claim:
          'Orange sweet potatoes provide 100-1600 ug RAE beta-carotene per 100g, sufficient to address vitamin A deficiency',
        evidence_level: 'strong',
        source_citation: 'Low et al., Adv Nutr 2017',
        pubmed_id: '28916574',
      },
      {
        claim:
          'Anthocyanins in purple sweet potato varieties show hepatoprotective effects in animal models',
        evidence_level: 'emerging',
        source_citation: 'Hwang et al., Food Chem 2011',
      },
    ],
  },
  {
    food_name: 'bitter gourd',
    claims: [
      {
        claim:
          'Charantin and polypeptide-p in bitter gourd mimic insulin action and reduce fasting glucose by 15-25% in diabetic subjects',
        evidence_level: 'moderate',
        source_citation: 'Joseph & Jini, J Ethnopharmacol 2013',
        pubmed_id: '23537660',
      },
      {
        claim:
          'Bitter gourd extract (2000mg/day) reduced HbA1c by 0.25% over 4 weeks in a randomized controlled trial',
        evidence_level: 'moderate',
        source_citation: 'Krawinkel & Keding, J Ethnopharmacol 2006',
      },
    ],
  },
  {
    food_name: 'ghee',
    claims: [
      {
        claim:
          'Conjugated linoleic acid (CLA) in ghee from grass-fed cows shows anti-atherogenic properties in animal studies',
        evidence_level: 'emerging',
        source_citation: 'Chinnadurai et al., Lipids Health Dis 2013',
      },
      {
        claim:
          'Short-chain fatty acids (butyrate) in ghee support intestinal mucosal health and reduce inflammation',
        evidence_level: 'moderate',
        source_citation: 'Sharma et al., Indian J Med Res 2010',
      },
    ],
  },
  {
    food_name: 'olive oil',
    claims: [
      {
        claim:
          'Extra virgin olive oil reduces cardiovascular events by 30% in the Mediterranean diet (PREDIMED trial)',
        evidence_level: 'strong',
        source_citation: 'Estruch et al., N Engl J Med 2013',
        pubmed_id: '23432189',
      },
      {
        claim:
          'Oleocanthal in EVOO has anti-inflammatory potency comparable to 10% of ibuprofen dose',
        evidence_level: 'moderate',
        source_citation: 'Beauchamp et al., Nature 2005',
        pubmed_id: '16136122',
      },
    ],
  },
  {
    food_name: 'coconut oil',
    claims: [
      {
        claim:
          'Medium-chain triglycerides (MCTs) in coconut oil increase energy expenditure by 5% compared to long-chain fats',
        evidence_level: 'moderate',
        source_citation: 'St-Onge & Jones, J Nutr 2002',
        pubmed_id: '12145024',
      },
      {
        claim:
          'Coconut oil raises both LDL and HDL cholesterol; net cardiovascular effect remains debated',
        evidence_level: 'moderate',
        source_citation: 'Neelakantan et al., Circulation 2020',
        pubmed_id: '31928080',
      },
    ],
  },
  {
    food_name: 'salmon',
    claims: [
      {
        claim:
          'EPA/DHA from fatty fish reduces triglycerides by 25-30% and cardiovascular mortality by 8-10%',
        evidence_level: 'strong',
        source_citation: 'Skulas-Ray et al., Circulation 2019',
        pubmed_id: '31422671',
      },
      {
        claim: 'Astaxanthin in wild salmon has 6000x stronger antioxidant capacity than vitamin C',
        evidence_level: 'moderate',
        source_citation: 'Ambati et al., Mar Drugs 2014',
        pubmed_id: '24413185',
      },
    ],
  },
  {
    food_name: 'green tea',
    claims: [
      {
        claim: 'EGCG in green tea increases fat oxidation by 17% during moderate exercise',
        evidence_level: 'moderate',
        source_citation: 'Venables et al., Am J Clin Nutr 2008',
        pubmed_id: '18258626',
      },
      {
        claim:
          'Regular green tea consumption (3+ cups/day) associated with 20-30% lower cardiovascular mortality risk',
        evidence_level: 'strong',
        source_citation: 'Kuriyama et al., JAMA 2006',
        pubmed_id: '16968850',
      },
    ],
  },
  {
    food_name: 'yogurt',
    claims: [
      {
        claim:
          'Probiotic yogurt consumption improves lactose digestion and reduces GI symptoms in lactose-intolerant individuals',
        evidence_level: 'strong',
        source_citation: 'EFSA Panel, EFSA Journal 2010',
      },
      {
        claim:
          'Daily yogurt intake is associated with 18% lower risk of type 2 diabetes in a meta-analysis of prospective studies',
        evidence_level: 'moderate',
        source_citation: 'Chen et al., BMC Med 2014',
        pubmed_id: '25159551',
      },
    ],
  },
  {
    food_name: 'avocado',
    claims: [
      {
        claim:
          'Daily avocado consumption reduces small dense LDL particles and oxidized LDL in overweight adults',
        evidence_level: 'strong',
        source_citation: 'Wang et al., J Am Heart Assoc 2015',
        pubmed_id: '25567051',
      },
      {
        claim:
          'Avocado lipid profile enhances absorption of fat-soluble carotenoids by 2-6x when eaten with other vegetables',
        evidence_level: 'moderate',
        source_citation: 'Unlu et al., J Nutr 2005',
        pubmed_id: '15735074',
      },
    ],
  },
  {
    food_name: 'pomegranate',
    claims: [
      {
        claim:
          'Pomegranate juice reduces systolic blood pressure by 5 mmHg through ACE inhibition (36% reduction in ACE activity)',
        evidence_level: 'moderate',
        source_citation: 'Aviram & Dornfeld, Atherosclerosis 2001',
        pubmed_id: '11369727',
      },
      {
        claim:
          'Punicalagins in pomegranate have 3x the antioxidant capacity of red wine or green tea per serving',
        evidence_level: 'moderate',
        source_citation: 'Seeram et al., J Agric Food Chem 2008',
        pubmed_id: '18159117',
      },
    ],
  },
  {
    food_name: 'tofu',
    claims: [
      {
        claim:
          'Soy isoflavones (40-80mg/day) reduce LDL cholesterol by 3-5% and may preserve bone density in postmenopausal women',
        evidence_level: 'moderate',
        source_citation: 'Sacks et al., Circulation 2006',
        pubmed_id: '16418439',
      },
      {
        claim:
          'Soy protein intake is associated with reduced breast cancer recurrence in Asian populations',
        evidence_level: 'moderate',
        source_citation: 'Shu et al., JAMA 2009',
        pubmed_id: '19996398',
      },
    ],
  },
  {
    food_name: 'almond',
    claims: [
      {
        claim:
          'Daily almond consumption (42g) reduces LDL cholesterol by 5.3% and increases HDL particle functionality',
        evidence_level: 'strong',
        source_citation: 'Berryman et al., J Am Heart Assoc 2015',
        pubmed_id: '25559009',
      },
      {
        claim:
          'Prebiotic fiber in almond skins increases Bifidobacteria and Lactobacillus counts in gut microbiome',
        evidence_level: 'moderate',
        source_citation: 'Liu et al., Anaerobe 2014',
        pubmed_id: '25057806',
      },
    ],
  },
  {
    food_name: 'honey',
    claims: [
      {
        claim:
          'Manuka honey has demonstrated bactericidal activity against antibiotic-resistant strains including MRSA in wound care',
        evidence_level: 'strong',
        source_citation: 'Molan, Burns 2001',
        pubmed_id: '11348531',
      },
      {
        claim:
          'Honey shows equivalent or superior efficacy to dextromethorphan for nighttime cough in children',
        evidence_level: 'strong',
        source_citation: 'Paul et al., Arch Pediatr Adolesc Med 2007',
        pubmed_id: '18056558',
      },
    ],
  },
  {
    food_name: 'dates',
    claims: [
      {
        claim:
          'Date fruit consumption in late pregnancy (6 dates/day for 4 weeks) reduces need for labor induction and augmentation',
        evidence_level: 'moderate',
        source_citation: 'Al-Kuran et al., J Obstet Gynaecol 2011',
        pubmed_id: '21280989',
      },
      {
        claim:
          'Polyphenols in dates (particularly caffeic acid) have demonstrated anti-mutagenic activity in cell culture',
        evidence_level: 'emerging',
        source_citation: 'Vayalil, J Agric Food Chem 2002',
      },
    ],
  },
  {
    food_name: 'beetroot',
    claims: [
      {
        claim:
          'Beetroot juice (500ml) reduces systolic blood pressure by 4-5 mmHg via nitric oxide pathway within 3 hours',
        evidence_level: 'strong',
        source_citation: 'Webb et al., Hypertension 2008',
        pubmed_id: '18250365',
      },
      {
        claim:
          'Dietary nitrates from beetroot improve exercise efficiency by 3-5% and time to exhaustion by 15-25%',
        evidence_level: 'strong',
        source_citation: 'Jones, Sports Med 2014',
        pubmed_id: '24791918',
      },
    ],
  },
  {
    food_name: 'broccoli',
    claims: [
      {
        claim:
          'Sulforaphane from broccoli activates Nrf2 antioxidant pathway and reduces fasting glucose in type 2 diabetes',
        evidence_level: 'moderate',
        source_citation: 'Axelsson et al., Sci Transl Med 2017',
        pubmed_id: '28615356',
      },
      {
        claim:
          'Cruciferous vegetable intake (3+ servings/week) associated with 33% lower risk of bladder cancer',
        evidence_level: 'moderate',
        source_citation: 'Tang et al., Int J Urol 2014',
      },
    ],
  },
  {
    food_name: 'garlic',
    claims: [
      {
        claim:
          'Aged garlic extract (600-1200mg/day) reduces systolic blood pressure by 8-11 mmHg in hypertensive patients',
        evidence_level: 'strong',
        source_citation: 'Ried et al., BMC Cardiovasc Disord 2008',
        pubmed_id: '18554422',
      },
      {
        claim:
          'Allicin from crushed garlic has broad-spectrum antimicrobial activity against bacteria, fungi, and viruses',
        evidence_level: 'moderate',
        source_citation: 'Ankri & Mirelman, Microbes Infect 1999',
        pubmed_id: '10611741',
      },
    ],
  },
  {
    food_name: 'ginger',
    claims: [
      {
        claim:
          'Ginger (1g/day) reduces nausea and vomiting in pregnancy with efficacy comparable to vitamin B6',
        evidence_level: 'strong',
        source_citation: 'Vutyavanich et al., Obstet Gynecol 2001',
        pubmed_id: '11267019',
      },
      {
        claim:
          '6-gingerol and 6-shogaol inhibit COX-2 and 5-LOX, providing dual anti-inflammatory action',
        evidence_level: 'moderate',
        source_citation: 'Mashhadi et al., Int J Prev Med 2013',
        pubmed_id: '23930179',
      },
    ],
  },
];

// -------------------------------------------------------------------------
// Seeder function
// -------------------------------------------------------------------------

/**
 * Seeds the evidence_claims table with curated scientific evidence.
 * Claims are append-only with duplicate checking on (food_id, claim).
 *
 * @param db - Database client (service role).
 * @param foodIdLookup - Map of lowercase food name to food UUID.
 * @returns Total number of evidence claim rows inserted.
 */
export async function seedEvidenceClaims(
  db: DbClient,
  foodIdLookup: Map<string, string>,
): Promise<number> {
  let insertedCount = 0;

  for (const entry of CANONICAL_EVIDENCE_CLAIMS) {
    const foodId = foodIdLookup.get(entry.food_name.toLowerCase());
    if (!foodId) continue;

    for (const claim of entry.claims) {
      // Check for exact duplicate before inserting (append-only pattern)
      const existing = await db
        .select({ id: evidenceClaims.id })
        .from(evidenceClaims)
        .where(and(eq(evidenceClaims.food_id, foodId), eq(evidenceClaims.claim, claim.claim)))
        .limit(1);

      if (existing.length > 0) continue;

      const row: NewEvidenceClaim = {
        food_id: foodId,
        claim: claim.claim,
        evidence_level: claim.evidence_level,
        source_citation: claim.source_citation,
        pubmed_id: claim.pubmed_id ?? null,
      };

      await db.insert(evidenceClaims).values(row);
      insertedCount++;
    }
  }

  return insertedCount;
}
