// Hardcoded seed data for the initial 50 foods.
// Each entry conforms to NewFood (minus id, created_at, updated_at which have defaults).
// Covers Indian, Chinese, Western, and Mediterranean cuisines.
//
// Ayurveda dosha effects: -2 strongly reduces, -1 reduces, 0 neutral, +1 aggravates, +2 strongly aggravates
// Ritu fit: 0-1 relevance score per Ayurvedic season
// Element fit: 0-1 affinity score per TCM element

import type { NewFood } from '../types.js';

type SeedFood = Omit<NewFood, 'id' | 'created_at' | 'updated_at'>;

export const FOOD_SEEDS: SeedFood[] = [
  // =========================================================================
  // GRAINS & CEREALS
  // =========================================================================
  {
    name: 'basmati rice',
    name_sanskrit: 'shali',
    name_chinese: 'xiang mi',
    category: 'grains',
    subcategory: 'rice',
    description: 'Long-grain aromatic rice, staple of Indian cuisine. Light and easy to digest.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.5, vasanta: 0.4, grishma: 0.9, varsha: 0.6, sharad: 0.7, hemanta: 0.5 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'stomach'],
    actions: ['tonify_qi', 'harmonize_middle'],
    element_fit: { wood: 0.3, fire: 0.2, earth: 0.9, metal: 0.4, water: 0.3 },
    glycemic_index: 58,
    bioactive_compounds: [{ name: 'thiamine', amount_per_100g: 0.07, unit: 'mg' }],
    contraindications: ['diabetes_uncontrolled'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'oats',
    name_sanskrit: null,
    name_chinese: 'yan mai',
    category: 'grains',
    subcategory: 'cereal',
    description: 'Whole grain oats, high in soluble fiber. Warming and nourishing.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.9, vasanta: 0.5, grishma: 0.3, varsha: 0.6, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'heart'],
    actions: ['tonify_qi', 'nourish_heart'],
    element_fit: { wood: 0.3, fire: 0.5, earth: 0.8, metal: 0.4, water: 0.3 },
    glycemic_index: 55,
    bioactive_compounds: [
      { name: 'beta-glucan', amount_per_100g: 4.0, unit: 'g' },
      { name: 'avenanthramides', amount_per_100g: 0.03, unit: 'mg' },
    ],
    contraindications: ['celiac_disease'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'quinoa',
    name_sanskrit: null,
    name_chinese: null,
    category: 'grains',
    subcategory: 'pseudocereal',
    description: 'Complete protein pseudocereal from South America. Light and astringent.',
    rasa: ['madhura', 'kashaya'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: 0,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.6, vasanta: 0.7, grishma: 0.5, varsha: 0.5, sharad: 0.6, hemanta: 0.6 },
    thermal_nature: 'warm',
    flavor: ['sweet', 'bitter'],
    organ_affinity: ['spleen', 'kidney'],
    actions: ['tonify_qi', 'drain_dampness'],
    element_fit: { wood: 0.4, fire: 0.4, earth: 0.7, metal: 0.5, water: 0.5 },
    glycemic_index: 53,
    bioactive_compounds: [
      { name: 'quercetin', amount_per_100g: 36.0, unit: 'mg' },
      { name: 'kaempferol', amount_per_100g: 15.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'millet',
    name_sanskrit: 'china',
    name_chinese: 'xiao mi',
    category: 'grains',
    subcategory: 'cereal',
    description:
      'Ancient grain widely consumed across India and China. Alkaline and easily digestible.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.4, vasanta: 0.7, grishma: 0.8, varsha: 0.5, sharad: 0.7, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet', 'salty'],
    organ_affinity: ['spleen', 'stomach', 'kidney'],
    actions: ['clear_heat', 'tonify_spleen'],
    element_fit: { wood: 0.3, fire: 0.3, earth: 0.8, metal: 0.5, water: 0.6 },
    glycemic_index: 62,
    bioactive_compounds: [{ name: 'iron', amount_per_100g: 3.0, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'barley',
    name_sanskrit: 'yava',
    name_chinese: 'da mai',
    category: 'grains',
    subcategory: 'cereal',
    description: 'Cooling grain excellent for kapha and pitta. Diuretic and cleansing.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -1,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.3, vasanta: 0.9, grishma: 0.8, varsha: 0.4, sharad: 0.7, hemanta: 0.3 },
    thermal_nature: 'cool',
    flavor: ['sweet', 'salty'],
    organ_affinity: ['spleen', 'stomach', 'bladder'],
    actions: ['drain_dampness', 'clear_heat', 'promote_urination'],
    element_fit: { wood: 0.4, fire: 0.2, earth: 0.7, metal: 0.6, water: 0.7 },
    glycemic_index: 28,
    bioactive_compounds: [
      { name: 'beta-glucan', amount_per_100g: 3.5, unit: 'g' },
      { name: 'tocotrienols', amount_per_100g: 1.2, unit: 'mg' },
    ],
    contraindications: ['celiac_disease'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // LEGUMES
  // =========================================================================
  {
    name: 'mung bean',
    name_sanskrit: 'mudga',
    name_chinese: 'lu dou',
    category: 'legumes',
    subcategory: 'bean',
    description:
      'The most sattvic and easily digestible legume in Ayurveda. Cooling and detoxifying.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: -2,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.4, vasanta: 0.7, grishma: 0.9, varsha: 0.7, sharad: 0.8, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['heart', 'stomach'],
    actions: ['clear_heat', 'resolve_toxin'],
    element_fit: { wood: 0.4, fire: 0.3, earth: 0.8, metal: 0.5, water: 0.5 },
    glycemic_index: 31,
    bioactive_compounds: [
      { name: 'vitexin', amount_per_100g: 12.0, unit: 'mg' },
      { name: 'isovitexin', amount_per_100g: 8.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'red lentil',
    name_sanskrit: 'masura',
    name_chinese: 'hong bian dou',
    category: 'legumes',
    subcategory: 'lentil',
    description: 'Quick-cooking split lentil, widely used in Indian dal. Moderately heating.',
    rasa: ['madhura', 'kashaya'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: 1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.7, vasanta: 0.5, grishma: 0.4, varsha: 0.6, sharad: 0.5, hemanta: 0.7 },
    thermal_nature: 'warm',
    flavor: ['sweet', 'astringent'],
    organ_affinity: ['spleen', 'kidney'],
    actions: ['tonify_qi', 'strengthen_spleen'],
    element_fit: { wood: 0.3, fire: 0.4, earth: 0.8, metal: 0.4, water: 0.5 },
    glycemic_index: 26,
    bioactive_compounds: [{ name: 'folate', amount_per_100g: 0.18, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'chickpea',
    name_sanskrit: 'chanaka',
    name_chinese: 'ying zui dou',
    category: 'legumes',
    subcategory: 'bean',
    description:
      'Versatile legume used in hummus, chana masala, and falafel. High protein and fiber.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['guru', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.5, vasanta: 0.6, grishma: 0.7, varsha: 0.4, sharad: 0.6, hemanta: 0.5 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'stomach'],
    actions: ['tonify_qi', 'promote_urination'],
    element_fit: { wood: 0.3, fire: 0.3, earth: 0.9, metal: 0.4, water: 0.4 },
    glycemic_index: 28,
    bioactive_compounds: [
      { name: 'saponins', amount_per_100g: 50.0, unit: 'mg' },
      { name: 'isoflavones', amount_per_100g: 3.6, unit: 'mg' },
    ],
    contraindications: ['bloating_prone'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // VEGETABLES
  // =========================================================================
  {
    name: 'spinach',
    name_sanskrit: 'palankya',
    name_chinese: 'bo cai',
    category: 'vegetables',
    subcategory: 'leafy_green',
    description: 'Iron-rich leafy green. Cooling and blood-building across all three traditions.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.4, vasanta: 0.7, grishma: 0.8, varsha: 0.5, sharad: 0.7, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['liver', 'large_intestine'],
    actions: ['nourish_blood', 'moisten_intestines'],
    element_fit: { wood: 0.7, fire: 0.3, earth: 0.5, metal: 0.6, water: 0.4 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'lutein', amount_per_100g: 12.2, unit: 'mg' },
      { name: 'beta-carotene', amount_per_100g: 5.6, unit: 'mg' },
    ],
    contraindications: ['kidney_stones_oxalate'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'sweet potato',
    name_sanskrit: 'madhura aluka',
    name_chinese: 'hong shu',
    category: 'vegetables',
    subcategory: 'root',
    description: 'Starchy root vegetable, naturally sweet. Excellent qi tonic in TCM.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.7, vasanta: 0.4, grishma: 0.5, varsha: 0.6, sharad: 0.8, hemanta: 0.8 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'kidney'],
    actions: ['tonify_qi', 'tonify_spleen'],
    element_fit: { wood: 0.3, fire: 0.3, earth: 0.9, metal: 0.4, water: 0.5 },
    glycemic_index: 63,
    bioactive_compounds: [
      { name: 'beta-carotene', amount_per_100g: 8.5, unit: 'mg' },
      { name: 'anthocyanins', amount_per_100g: 14.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'bitter gourd',
    name_sanskrit: 'karavella',
    name_chinese: 'ku gua',
    category: 'vegetables',
    subcategory: 'gourd',
    description: 'Intensely bitter vegetable, prized in Ayurveda for blood sugar management.',
    rasa: ['tikta', 'katu'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -2,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.2, vasanta: 0.8, grishma: 0.9, varsha: 0.6, sharad: 0.7, hemanta: 0.2 },
    thermal_nature: 'cold',
    flavor: ['bitter'],
    organ_affinity: ['heart', 'liver', 'lung'],
    actions: ['clear_heat', 'resolve_toxin', 'brighten_eyes'],
    element_fit: { wood: 0.7, fire: 0.8, earth: 0.2, metal: 0.5, water: 0.3 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'charantin', amount_per_100g: 18.0, unit: 'mg' },
      { name: 'momordicin', amount_per_100g: 5.0, unit: 'mg' },
    ],
    contraindications: ['pregnancy', 'hypoglycemia'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'broccoli',
    name_sanskrit: null,
    name_chinese: 'xi lan hua',
    category: 'vegetables',
    subcategory: 'cruciferous',
    description: 'Nutrient-dense cruciferous vegetable, rich in sulforaphane.',
    rasa: ['tikta', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.5, vasanta: 0.7, grishma: 0.6, varsha: 0.5, sharad: 0.7, hemanta: 0.5 },
    thermal_nature: 'cool',
    flavor: ['sweet', 'bitter'],
    organ_affinity: ['liver', 'spleen'],
    actions: ['clear_heat', 'promote_digestion'],
    element_fit: { wood: 0.7, fire: 0.3, earth: 0.5, metal: 0.6, water: 0.3 },
    glycemic_index: 10,
    bioactive_compounds: [
      { name: 'sulforaphane', amount_per_100g: 44.0, unit: 'mg' },
      { name: 'indole-3-carbinol', amount_per_100g: 24.0, unit: 'mg' },
    ],
    contraindications: ['hypothyroidism_raw'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'pumpkin',
    name_sanskrit: 'kusmanda',
    name_chinese: 'nan gua',
    category: 'vegetables',
    subcategory: 'gourd',
    description: 'Sweet, warming gourd. Excellent for spleen and stomach in both Ayurveda and TCM.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.7, vasanta: 0.4, grishma: 0.4, varsha: 0.6, sharad: 0.9, hemanta: 0.8 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'stomach'],
    actions: ['tonify_qi', 'regulate_middle'],
    element_fit: { wood: 0.2, fire: 0.4, earth: 0.9, metal: 0.3, water: 0.3 },
    glycemic_index: 75,
    bioactive_compounds: [
      { name: 'beta-carotene', amount_per_100g: 3.1, unit: 'mg' },
      { name: 'cucurbitacin', amount_per_100g: 2.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'zucchini',
    name_sanskrit: null,
    name_chinese: 'xi hu lu',
    category: 'vegetables',
    subcategory: 'squash',
    description: 'Light summer squash, cooling and easy to digest. Good for pitta season.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: 0,
    pitta_effect: -1,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.3, vasanta: 0.5, grishma: 0.9, varsha: 0.6, sharad: 0.6, hemanta: 0.3 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'stomach', 'lung'],
    actions: ['clear_heat', 'promote_urination'],
    element_fit: { wood: 0.3, fire: 0.2, earth: 0.7, metal: 0.5, water: 0.5 },
    glycemic_index: 15,
    bioactive_compounds: [{ name: 'lutein', amount_per_100g: 2.1, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'beetroot',
    name_sanskrit: 'palandu rakta',
    name_chinese: 'tian cai gen',
    category: 'vegetables',
    subcategory: 'root',
    description: 'Deep red root vegetable, rich in nitrates and betalains. Blood-building.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.6, vasanta: 0.5, grishma: 0.4, varsha: 0.5, sharad: 0.7, hemanta: 0.7 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['heart', 'liver'],
    actions: ['nourish_blood', 'invigorate_blood'],
    element_fit: { wood: 0.5, fire: 0.6, earth: 0.6, metal: 0.3, water: 0.4 },
    glycemic_index: 61,
    bioactive_compounds: [
      { name: 'betalains', amount_per_100g: 120.0, unit: 'mg' },
      { name: 'nitrate', amount_per_100g: 250.0, unit: 'mg' },
    ],
    contraindications: ['kidney_stones_oxalate'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'cauliflower',
    name_sanskrit: 'gobi',
    name_chinese: 'hua cai',
    category: 'vegetables',
    subcategory: 'cruciferous',
    description: 'Versatile cruciferous vegetable, lighter than broccoli. Reduces kapha.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.4, vasanta: 0.7, grishma: 0.6, varsha: 0.5, sharad: 0.7, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'large_intestine'],
    actions: ['promote_digestion', 'drain_dampness'],
    element_fit: { wood: 0.4, fire: 0.2, earth: 0.6, metal: 0.7, water: 0.3 },
    glycemic_index: 15,
    bioactive_compounds: [{ name: 'sulforaphane', amount_per_100g: 28.0, unit: 'mg' }],
    contraindications: ['hypothyroidism_raw'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'okra',
    name_sanskrit: 'bhinda',
    name_chinese: 'qiu kui',
    category: 'vegetables',
    subcategory: 'fruit_vegetable',
    description: 'Mucilaginous vegetable common in Indian and Southern US cooking. Lubricating.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha', 'picchila'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.4, vasanta: 0.5, grishma: 0.8, varsha: 0.7, sharad: 0.6, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'kidney'],
    actions: ['moisten_dryness', 'tonify_yin'],
    element_fit: { wood: 0.3, fire: 0.2, earth: 0.7, metal: 0.4, water: 0.6 },
    glycemic_index: 20,
    bioactive_compounds: [{ name: 'mucilage', amount_per_100g: 1500.0, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // FRUITS
  // =========================================================================
  {
    name: 'pomegranate',
    name_sanskrit: 'dadima',
    name_chinese: 'shi liu',
    category: 'fruits',
    subcategory: 'berry',
    description: 'Ancient fruit revered across all three traditions. Balances all three doshas.',
    rasa: ['madhura', 'amla', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.5, vasanta: 0.6, grishma: 0.7, varsha: 0.5, sharad: 0.9, hemanta: 0.6 },
    thermal_nature: 'neutral',
    flavor: ['sweet', 'sour', 'astringent'],
    organ_affinity: ['heart', 'kidney', 'large_intestine'],
    actions: ['astringent', 'nourish_blood', 'generate_fluid'],
    element_fit: { wood: 0.5, fire: 0.5, earth: 0.6, metal: 0.6, water: 0.5 },
    glycemic_index: 35,
    bioactive_compounds: [
      { name: 'punicalagin', amount_per_100g: 200.0, unit: 'mg' },
      { name: 'ellagic_acid', amount_per_100g: 55.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'mango',
    name_sanskrit: 'amra',
    name_chinese: 'mang guo',
    category: 'fruits',
    subcategory: 'tropical',
    description: 'King of fruits. Ripe mango is sweet and cooling; raw mango is sour and heating.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.3, vasanta: 0.4, grishma: 0.9, varsha: 0.5, sharad: 0.5, hemanta: 0.3 },
    thermal_nature: 'cool',
    flavor: ['sweet', 'sour'],
    organ_affinity: ['stomach', 'spleen'],
    actions: ['generate_fluid', 'relieve_thirst'],
    element_fit: { wood: 0.4, fire: 0.3, earth: 0.8, metal: 0.3, water: 0.4 },
    glycemic_index: 51,
    bioactive_compounds: [
      { name: 'mangiferin', amount_per_100g: 4.5, unit: 'mg' },
      { name: 'beta-carotene', amount_per_100g: 1.0, unit: 'mg' },
    ],
    contraindications: ['diabetes_excess'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'banana',
    name_sanskrit: 'kadali',
    name_chinese: 'xiang jiao',
    category: 'fruits',
    subcategory: 'tropical',
    description: 'Widely available energy fruit. Heavy, sweet, and mildly laxative.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'amla',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.5, vasanta: 0.4, grishma: 0.7, varsha: 0.5, sharad: 0.6, hemanta: 0.5 },
    thermal_nature: 'cold',
    flavor: ['sweet'],
    organ_affinity: ['lung', 'large_intestine'],
    actions: ['clear_heat', 'moisten_intestines'],
    element_fit: { wood: 0.3, fire: 0.2, earth: 0.8, metal: 0.5, water: 0.4 },
    glycemic_index: 51,
    bioactive_compounds: [
      { name: 'potassium', amount_per_100g: 358.0, unit: 'mg' },
      { name: 'dopamine', amount_per_100g: 10.0, unit: 'mg' },
    ],
    contraindications: ['cold_constitution'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'apple',
    name_sanskrit: 'seba',
    name_chinese: 'ping guo',
    category: 'fruits',
    subcategory: 'pome',
    description: 'Common temperate fruit, mildly astringent and cooling.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: -1,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.5, vasanta: 0.5, grishma: 0.6, varsha: 0.5, sharad: 0.9, hemanta: 0.5 },
    thermal_nature: 'cool',
    flavor: ['sweet', 'sour'],
    organ_affinity: ['spleen', 'lung'],
    actions: ['generate_fluid', 'moisten_lung'],
    element_fit: { wood: 0.4, fire: 0.3, earth: 0.6, metal: 0.7, water: 0.4 },
    glycemic_index: 36,
    bioactive_compounds: [
      { name: 'quercetin', amount_per_100g: 4.4, unit: 'mg' },
      { name: 'phloridzin', amount_per_100g: 0.5, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'dates',
    name_sanskrit: 'kharjura',
    name_chinese: 'zao',
    category: 'fruits',
    subcategory: 'dried_fruit',
    description:
      'Naturally sweet dried fruit, rich in iron. Powerful vata pacifier and energy source.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -2,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.8, vasanta: 0.3, grishma: 0.5, varsha: 0.5, sharad: 0.6, hemanta: 0.8 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'lung', 'kidney'],
    actions: ['tonify_qi', 'tonify_blood', 'moisten_lung'],
    element_fit: { wood: 0.3, fire: 0.4, earth: 0.9, metal: 0.5, water: 0.5 },
    glycemic_index: 42,
    bioactive_compounds: [
      { name: 'iron', amount_per_100g: 1.0, unit: 'mg' },
      { name: 'tannins', amount_per_100g: 350.0, unit: 'mg' },
    ],
    contraindications: ['diabetes_uncontrolled'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // DAIRY & ANIMAL PRODUCTS
  // =========================================================================
  {
    name: 'ghee',
    name_sanskrit: 'ghrta',
    name_chinese: 'su you',
    category: 'dairy',
    subcategory: 'clarified_fat',
    description:
      'Clarified butter, considered the most sattvic fat in Ayurveda. Enhances ojas and agni.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['snigdha', 'mridu'],
    vata_effect: -2,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.8, vasanta: 0.4, grishma: 0.6, varsha: 0.5, sharad: 0.7, hemanta: 0.9 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'stomach', 'kidney'],
    actions: ['tonify_yin', 'moisten_dryness'],
    element_fit: { wood: 0.3, fire: 0.3, earth: 0.8, metal: 0.4, water: 0.6 },
    glycemic_index: 0,
    bioactive_compounds: [
      { name: 'butyrate', amount_per_100g: 3.0, unit: 'g' },
      { name: 'conjugated_linoleic_acid', amount_per_100g: 0.6, unit: 'g' },
    ],
    contraindications: ['hypercholesterolemia'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'yogurt',
    name_sanskrit: 'dadhi',
    name_chinese: 'suan nai',
    category: 'dairy',
    subcategory: 'fermented',
    description: 'Fermented milk product, sour and heavy. Good for vata but increases kapha.',
    rasa: ['amla', 'madhura'],
    virya: 'ushna',
    vipaka: 'amla',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.3, vasanta: 0.3, grishma: 0.4, varsha: 0.2, sharad: 0.4, hemanta: 0.5 },
    thermal_nature: 'warm',
    flavor: ['sour', 'sweet'],
    organ_affinity: ['spleen', 'stomach', 'large_intestine'],
    actions: ['generate_fluid', 'tonify_yin'],
    element_fit: { wood: 0.5, fire: 0.5, earth: 0.7, metal: 0.3, water: 0.4 },
    glycemic_index: 36,
    bioactive_compounds: [
      { name: 'probiotics', amount_per_100g: 1000000.0, unit: 'CFU' },
      { name: 'calcium', amount_per_100g: 110.0, unit: 'mg' },
    ],
    contraindications: ['lactose_intolerance', 'kapha_excess'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'paneer',
    name_sanskrit: 'paneer',
    name_chinese: null,
    category: 'dairy',
    subcategory: 'cheese',
    description: 'Fresh Indian cottage cheese, high in protein. Sweet, cooling, and heavy.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.6, vasanta: 0.3, grishma: 0.5, varsha: 0.4, sharad: 0.6, hemanta: 0.7 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'kidney'],
    actions: ['tonify_yin', 'strengthen_bone'],
    element_fit: { wood: 0.3, fire: 0.2, earth: 0.8, metal: 0.4, water: 0.5 },
    glycemic_index: 0,
    bioactive_compounds: [{ name: 'casein', amount_per_100g: 18.0, unit: 'g' }],
    contraindications: ['lactose_intolerance'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'chicken',
    name_sanskrit: 'kukkuta mamsa',
    name_chinese: 'ji rou',
    category: 'protein',
    subcategory: 'poultry',
    description: 'Lean poultry meat, warming and nourishing. Builds dhatu tissues in Ayurveda.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.8, vasanta: 0.4, grishma: 0.3, varsha: 0.6, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'stomach'],
    actions: ['tonify_qi', 'warm_middle'],
    element_fit: { wood: 0.3, fire: 0.5, earth: 0.8, metal: 0.3, water: 0.4 },
    glycemic_index: 0,
    bioactive_compounds: [{ name: 'carnosine', amount_per_100g: 350.0, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'salmon',
    name_sanskrit: null,
    name_chinese: 'gui yu',
    category: 'protein',
    subcategory: 'fish',
    description: 'Cold-water fatty fish, rich in omega-3. Tonifies qi and nourishes yin.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.8, vasanta: 0.4, grishma: 0.3, varsha: 0.5, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'kidney'],
    actions: ['tonify_qi', 'nourish_blood'],
    element_fit: { wood: 0.3, fire: 0.4, earth: 0.6, metal: 0.4, water: 0.7 },
    glycemic_index: 0,
    bioactive_compounds: [
      { name: 'EPA', amount_per_100g: 0.9, unit: 'g' },
      { name: 'DHA', amount_per_100g: 1.1, unit: 'g' },
      { name: 'astaxanthin', amount_per_100g: 4.0, unit: 'mg' },
    ],
    contraindications: ['fish_allergy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'egg',
    name_sanskrit: 'anda',
    name_chinese: 'ji dan',
    category: 'protein',
    subcategory: 'egg',
    description: 'Complete protein source, highly nourishing. Sweet, warm, and heavy.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.7, vasanta: 0.4, grishma: 0.3, varsha: 0.5, sharad: 0.5, hemanta: 0.8 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['heart', 'kidney'],
    actions: ['tonify_blood', 'nourish_yin'],
    element_fit: { wood: 0.3, fire: 0.4, earth: 0.7, metal: 0.4, water: 0.6 },
    glycemic_index: 0,
    bioactive_compounds: [
      { name: 'choline', amount_per_100g: 294.0, unit: 'mg' },
      { name: 'lutein', amount_per_100g: 0.5, unit: 'mg' },
    ],
    contraindications: ['egg_allergy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // SPICES & CONDIMENTS
  // =========================================================================
  {
    name: 'turmeric',
    name_sanskrit: 'haridra',
    name_chinese: 'jiang huang',
    category: 'spices',
    subcategory: 'rhizome',
    description: 'Golden anti-inflammatory spice central to all three traditions.',
    rasa: ['tikta', 'katu'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: 0,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.7, vasanta: 0.8, grishma: 0.4, varsha: 0.8, sharad: 0.6, hemanta: 0.7 },
    thermal_nature: 'warm',
    flavor: ['bitter', 'pungent'],
    organ_affinity: ['liver', 'spleen'],
    actions: ['invigorate_blood', 'clear_heat', 'resolve_toxin'],
    element_fit: { wood: 0.7, fire: 0.6, earth: 0.5, metal: 0.4, water: 0.3 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'curcumin', amount_per_100g: 3100.0, unit: 'mg' },
      { name: 'turmerone', amount_per_100g: 200.0, unit: 'mg' },
    ],
    contraindications: ['gallstones', 'blood_thinners'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'ginger',
    name_sanskrit: 'shunti',
    name_chinese: 'sheng jiang',
    category: 'spices',
    subcategory: 'rhizome',
    description:
      'Universal digestive aid across all traditions. Fresh is cooling, dried is heating.',
    rasa: ['katu'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.9, vasanta: 0.7, grishma: 0.3, varsha: 0.8, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'warm',
    flavor: ['pungent'],
    organ_affinity: ['lung', 'spleen', 'stomach'],
    actions: ['warm_middle', 'resolve_phlegm', 'disperse_cold'],
    element_fit: { wood: 0.4, fire: 0.7, earth: 0.6, metal: 0.6, water: 0.3 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'gingerol', amount_per_100g: 1800.0, unit: 'mg' },
      { name: 'shogaol', amount_per_100g: 300.0, unit: 'mg' },
    ],
    contraindications: ['gastric_ulcer', 'blood_thinners'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'cumin',
    name_sanskrit: 'jiraka',
    name_chinese: 'zi ran',
    category: 'spices',
    subcategory: 'seed_spice',
    description:
      'Essential digestive spice in Indian cooking. Kindles agni without aggravating pitta.',
    rasa: ['katu'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.7, vasanta: 0.6, grishma: 0.4, varsha: 0.8, sharad: 0.5, hemanta: 0.7 },
    thermal_nature: 'warm',
    flavor: ['pungent'],
    organ_affinity: ['spleen', 'stomach'],
    actions: ['promote_digestion', 'regulate_qi'],
    element_fit: { wood: 0.4, fire: 0.6, earth: 0.7, metal: 0.5, water: 0.3 },
    glycemic_index: 15,
    bioactive_compounds: [{ name: 'cuminaldehyde', amount_per_100g: 2500.0, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'cinnamon',
    name_sanskrit: 'tvak',
    name_chinese: 'rou gui',
    category: 'spices',
    subcategory: 'bark',
    description: 'Warming bark spice, promotes circulation and regulates blood sugar.',
    rasa: ['katu', 'madhura'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha', 'tikshna'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.9, vasanta: 0.5, grishma: 0.2, varsha: 0.7, sharad: 0.4, hemanta: 0.9 },
    thermal_nature: 'hot',
    flavor: ['pungent', 'sweet'],
    organ_affinity: ['kidney', 'spleen', 'heart'],
    actions: ['warm_kidney', 'disperse_cold', 'invigorate_blood'],
    element_fit: { wood: 0.3, fire: 0.8, earth: 0.5, metal: 0.4, water: 0.5 },
    glycemic_index: 10,
    bioactive_compounds: [
      { name: 'cinnamaldehyde', amount_per_100g: 18000.0, unit: 'mg' },
      { name: 'coumarin', amount_per_100g: 5.0, unit: 'mg' },
    ],
    contraindications: ['pregnancy_excess', 'liver_disease'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'black pepper',
    name_sanskrit: 'maricha',
    name_chinese: 'hu jiao',
    category: 'spices',
    subcategory: 'seed_spice',
    description: 'King of spices. Strongly heating, enhances bioavailability of other compounds.',
    rasa: ['katu'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha', 'tikshna'],
    vata_effect: -1,
    pitta_effect: 2,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.9, vasanta: 0.6, grishma: 0.2, varsha: 0.8, sharad: 0.4, hemanta: 0.9 },
    thermal_nature: 'hot',
    flavor: ['pungent'],
    organ_affinity: ['stomach', 'large_intestine', 'lung'],
    actions: ['warm_middle', 'resolve_phlegm', 'promote_digestion'],
    element_fit: { wood: 0.3, fire: 0.8, earth: 0.5, metal: 0.6, water: 0.2 },
    glycemic_index: 10,
    bioactive_compounds: [{ name: 'piperine', amount_per_100g: 5900.0, unit: 'mg' }],
    contraindications: ['gastric_ulcer', 'pitta_excess'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'coriander',
    name_sanskrit: 'dhanyaka',
    name_chinese: 'xiang cai',
    category: 'spices',
    subcategory: 'seed_spice',
    description: 'Cooling digestive spice. One of the few spices that calms all three doshas.',
    rasa: ['katu', 'tikta', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.4, vasanta: 0.7, grishma: 0.9, varsha: 0.6, sharad: 0.7, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['pungent', 'sweet'],
    organ_affinity: ['lung', 'stomach'],
    actions: ['promote_digestion', 'regulate_qi', 'clear_heat'],
    element_fit: { wood: 0.5, fire: 0.4, earth: 0.6, metal: 0.7, water: 0.4 },
    glycemic_index: 10,
    bioactive_compounds: [{ name: 'linalool', amount_per_100g: 6500.0, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'fenugreek',
    name_sanskrit: 'methi',
    name_chinese: 'hu lu ba',
    category: 'spices',
    subcategory: 'seed_spice',
    description:
      'Bitter seed spice used in Indian cooking. Blood sugar regulator and galactagogue.',
    rasa: ['tikta', 'katu'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.7, vasanta: 0.6, grishma: 0.3, varsha: 0.7, sharad: 0.5, hemanta: 0.8 },
    thermal_nature: 'warm',
    flavor: ['bitter', 'pungent'],
    organ_affinity: ['kidney', 'liver'],
    actions: ['warm_kidney', 'tonify_yang'],
    element_fit: { wood: 0.5, fire: 0.6, earth: 0.5, metal: 0.4, water: 0.6 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'trigonelline', amount_per_100g: 760.0, unit: 'mg' },
      { name: 'diosgenin', amount_per_100g: 400.0, unit: 'mg' },
    ],
    contraindications: ['pregnancy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'cardamom',
    name_sanskrit: 'ela',
    name_chinese: 'bai dou kou',
    category: 'spices',
    subcategory: 'pod_spice',
    description: 'Queen of spices. Aromatic, mildly warming, excellent digestive.',
    rasa: ['katu', 'madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.6, vasanta: 0.6, grishma: 0.5, varsha: 0.7, sharad: 0.6, hemanta: 0.7 },
    thermal_nature: 'warm',
    flavor: ['pungent', 'sweet'],
    organ_affinity: ['lung', 'spleen', 'stomach'],
    actions: ['regulate_qi', 'resolve_dampness', 'warm_middle'],
    element_fit: { wood: 0.4, fire: 0.5, earth: 0.7, metal: 0.6, water: 0.3 },
    glycemic_index: 10,
    bioactive_compounds: [{ name: '1,8-cineole', amount_per_100g: 3600.0, unit: 'mg' }],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // NUTS & SEEDS
  // =========================================================================
  {
    name: 'almond',
    name_sanskrit: 'vatada',
    name_chinese: 'xing ren',
    category: 'nuts_seeds',
    subcategory: 'tree_nut',
    description: 'Nourishing nut, builds ojas in Ayurveda. Best soaked and peeled.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -2,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.9, vasanta: 0.4, grishma: 0.3, varsha: 0.5, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['lung', 'large_intestine'],
    actions: ['moisten_lung', 'descend_qi'],
    element_fit: { wood: 0.3, fire: 0.3, earth: 0.7, metal: 0.7, water: 0.5 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'vitamin_E', amount_per_100g: 25.6, unit: 'mg' },
      { name: 'magnesium', amount_per_100g: 270.0, unit: 'mg' },
    ],
    contraindications: ['nut_allergy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'sesame seed',
    name_sanskrit: 'tila',
    name_chinese: 'hei zhi ma',
    category: 'nuts_seeds',
    subcategory: 'seed',
    description: 'Ancient oilseed. Black sesame nourishes kidney yin in TCM. Builds bones.',
    rasa: ['madhura', 'tikta'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.8, vasanta: 0.4, grishma: 0.3, varsha: 0.5, sharad: 0.6, hemanta: 0.9 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['liver', 'kidney'],
    actions: ['tonify_liver', 'tonify_kidney', 'nourish_blood'],
    element_fit: { wood: 0.5, fire: 0.4, earth: 0.6, metal: 0.4, water: 0.8 },
    glycemic_index: 35,
    bioactive_compounds: [
      { name: 'sesamin', amount_per_100g: 340.0, unit: 'mg' },
      { name: 'sesamol', amount_per_100g: 25.0, unit: 'mg' },
    ],
    contraindications: ['sesame_allergy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'walnut',
    name_sanskrit: 'akshota',
    name_chinese: 'he tao',
    category: 'nuts_seeds',
    subcategory: 'tree_nut',
    description: 'Brain-shaped nut rich in omega-3. Nourishes brain and kidney yang in TCM.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.9, vasanta: 0.3, grishma: 0.2, varsha: 0.5, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['kidney', 'lung', 'large_intestine'],
    actions: ['tonify_kidney', 'warm_lung', 'moisten_intestines'],
    element_fit: { wood: 0.3, fire: 0.4, earth: 0.5, metal: 0.5, water: 0.8 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'ALA', amount_per_100g: 9.1, unit: 'g' },
      { name: 'ellagic_acid', amount_per_100g: 59.0, unit: 'mg' },
    ],
    contraindications: ['nut_allergy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'flaxseed',
    name_sanskrit: 'atasi',
    name_chinese: 'ya ma zi',
    category: 'nuts_seeds',
    subcategory: 'seed',
    description: 'Omega-3 rich seed. Must be ground for nutrient absorption. Mildly laxative.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.7, vasanta: 0.5, grishma: 0.4, varsha: 0.5, sharad: 0.5, hemanta: 0.7 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['liver', 'large_intestine'],
    actions: ['moisten_intestines', 'nourish_yin'],
    element_fit: { wood: 0.5, fire: 0.3, earth: 0.5, metal: 0.5, water: 0.7 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'ALA', amount_per_100g: 22.8, unit: 'g' },
      { name: 'lignans', amount_per_100g: 300.0, unit: 'mg' },
    ],
    contraindications: ['bowel_obstruction'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // OILS & FATS
  // =========================================================================
  {
    name: 'coconut oil',
    name_sanskrit: 'narikela taila',
    name_chinese: 'ye zi you',
    category: 'oils',
    subcategory: 'plant_oil',
    description: 'Cooling saturated fat from coconut. Excellent for pitta pacification.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.3, vasanta: 0.4, grishma: 0.9, varsha: 0.5, sharad: 0.7, hemanta: 0.3 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'large_intestine'],
    actions: ['moisten_dryness', 'tonify_yin'],
    element_fit: { wood: 0.3, fire: 0.2, earth: 0.7, metal: 0.5, water: 0.6 },
    glycemic_index: 0,
    bioactive_compounds: [
      { name: 'lauric_acid', amount_per_100g: 47.0, unit: 'g' },
      { name: 'MCT', amount_per_100g: 15.0, unit: 'g' },
    ],
    contraindications: ['coconut_allergy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'olive oil',
    name_sanskrit: null,
    name_chinese: 'gan lan you',
    category: 'oils',
    subcategory: 'plant_oil',
    description: 'Mediterranean staple oil. Rich in oleic acid and polyphenols.',
    rasa: ['madhura', 'tikta'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.6, vasanta: 0.5, grishma: 0.4, varsha: 0.5, sharad: 0.6, hemanta: 0.7 },
    thermal_nature: 'neutral',
    flavor: ['sweet', 'bitter'],
    organ_affinity: ['liver', 'stomach'],
    actions: ['nourish_yin', 'moisten_dryness'],
    element_fit: { wood: 0.6, fire: 0.3, earth: 0.6, metal: 0.4, water: 0.5 },
    glycemic_index: 0,
    bioactive_compounds: [
      { name: 'oleocanthal', amount_per_100g: 200.0, unit: 'mg' },
      { name: 'hydroxytyrosol', amount_per_100g: 14.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // SWEETENERS
  // =========================================================================
  {
    name: 'honey',
    name_sanskrit: 'madhu',
    name_chinese: 'feng mi',
    category: 'sweeteners',
    subcategory: 'natural',
    description:
      'Natural sweetener, considered medicine in Ayurveda. Never cook or heat honey per Ayurveda.',
    rasa: ['madhura', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: 0,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.5, vasanta: 0.9, grishma: 0.4, varsha: 0.5, sharad: 0.6, hemanta: 0.5 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['lung', 'spleen', 'large_intestine'],
    actions: ['tonify_qi', 'moisten_dryness', 'resolve_toxin'],
    element_fit: { wood: 0.3, fire: 0.3, earth: 0.8, metal: 0.6, water: 0.4 },
    glycemic_index: 58,
    bioactive_compounds: [
      { name: 'hydrogen_peroxide', amount_per_100g: 1.0, unit: 'mmol' },
      { name: 'methylglyoxal', amount_per_100g: 0.3, unit: 'mg' },
    ],
    contraindications: ['diabetes_uncontrolled', 'infant_under_1'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'jaggery',
    name_sanskrit: 'guda',
    name_chinese: null,
    category: 'sweeteners',
    subcategory: 'natural',
    description:
      'Unrefined cane sugar common in Indian cooking. Retains minerals lost in refining.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.7, vasanta: 0.3, grishma: 0.3, varsha: 0.5, sharad: 0.5, hemanta: 0.7 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'liver'],
    actions: ['tonify_qi', 'nourish_blood'],
    element_fit: { wood: 0.4, fire: 0.5, earth: 0.8, metal: 0.3, water: 0.3 },
    glycemic_index: 84,
    bioactive_compounds: [
      { name: 'iron', amount_per_100g: 11.0, unit: 'mg' },
      { name: 'potassium', amount_per_100g: 1050.0, unit: 'mg' },
    ],
    contraindications: ['diabetes_uncontrolled'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // CHINESE / EAST ASIAN FOODS
  // =========================================================================
  {
    name: 'tofu',
    name_sanskrit: null,
    name_chinese: 'dou fu',
    category: 'protein',
    subcategory: 'soy',
    description: 'Soybean curd, a TCM staple. Cooling, moistening, and high in plant protein.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: 0,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.4, vasanta: 0.5, grishma: 0.8, varsha: 0.5, sharad: 0.6, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['spleen', 'stomach', 'large_intestine'],
    actions: ['clear_heat', 'generate_fluid', 'resolve_toxin'],
    element_fit: { wood: 0.4, fire: 0.2, earth: 0.7, metal: 0.4, water: 0.5 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'genistein', amount_per_100g: 25.0, unit: 'mg' },
      { name: 'daidzein', amount_per_100g: 20.0, unit: 'mg' },
    ],
    contraindications: ['soy_allergy', 'estrogen_sensitive'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'miso',
    name_sanskrit: null,
    name_chinese: 'wei zeng',
    category: 'condiments',
    subcategory: 'fermented_paste',
    description: 'Fermented soybean paste, rich in probiotics and umami. Warming and tonifying.',
    rasa: ['lavana', 'madhura'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.8, vasanta: 0.5, grishma: 0.3, varsha: 0.6, sharad: 0.5, hemanta: 0.8 },
    thermal_nature: 'warm',
    flavor: ['salty', 'sweet'],
    organ_affinity: ['spleen', 'stomach', 'kidney'],
    actions: ['warm_middle', 'promote_digestion', 'resolve_toxin'],
    element_fit: { wood: 0.3, fire: 0.5, earth: 0.7, metal: 0.4, water: 0.6 },
    glycemic_index: 33,
    bioactive_compounds: [
      { name: 'isoflavones', amount_per_100g: 42.5, unit: 'mg' },
      { name: 'probiotics', amount_per_100g: 500000.0, unit: 'CFU' },
    ],
    contraindications: ['soy_allergy', 'hypertension_sodium'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'goji berry',
    name_sanskrit: null,
    name_chinese: 'gou qi zi',
    category: 'fruits',
    subcategory: 'berry',
    description: 'Prized TCM tonic fruit. Nourishes liver and kidney yin, brightens eyes.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.6, vasanta: 0.5, grishma: 0.5, varsha: 0.5, sharad: 0.7, hemanta: 0.7 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['liver', 'kidney', 'lung'],
    actions: ['tonify_liver', 'tonify_kidney', 'brighten_eyes'],
    element_fit: { wood: 0.7, fire: 0.3, earth: 0.5, metal: 0.4, water: 0.7 },
    glycemic_index: 29,
    bioactive_compounds: [
      { name: 'zeaxanthin', amount_per_100g: 26.0, unit: 'mg' },
      { name: 'betaine', amount_per_100g: 5.0, unit: 'mg' },
    ],
    contraindications: ['blood_thinners'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'bok choy',
    name_sanskrit: null,
    name_chinese: 'xiao bai cai',
    category: 'vegetables',
    subcategory: 'leafy_green',
    description: 'Chinese cabbage, cooling and mineral-rich. Excellent heat-clearing green.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.3, vasanta: 0.6, grishma: 0.8, varsha: 0.5, sharad: 0.7, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['lung', 'stomach', 'large_intestine'],
    actions: ['clear_heat', 'promote_urination'],
    element_fit: { wood: 0.4, fire: 0.2, earth: 0.5, metal: 0.7, water: 0.4 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'calcium', amount_per_100g: 105.0, unit: 'mg' },
      { name: 'glucosinolates', amount_per_100g: 54.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'shiitake mushroom',
    name_sanskrit: null,
    name_chinese: 'xiang gu',
    category: 'vegetables',
    subcategory: 'mushroom',
    description: 'Medicinal mushroom prized in TCM and Japanese cuisine. Tonifies qi and wei qi.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: 0,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.5, vasanta: 0.7, grishma: 0.5, varsha: 0.7, sharad: 0.7, hemanta: 0.6 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['stomach', 'lung'],
    actions: ['tonify_qi', 'strengthen_wei_qi'],
    element_fit: { wood: 0.5, fire: 0.3, earth: 0.8, metal: 0.5, water: 0.4 },
    glycemic_index: 10,
    bioactive_compounds: [
      { name: 'lentinan', amount_per_100g: 1600.0, unit: 'mg' },
      { name: 'eritadenine', amount_per_100g: 40.0, unit: 'mg' },
    ],
    contraindications: ['mushroom_allergy'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // MEDITERRANEAN FOODS
  // =========================================================================
  {
    name: 'garlic',
    name_sanskrit: 'lashuna',
    name_chinese: 'da suan',
    category: 'vegetables',
    subcategory: 'allium',
    description: 'Pungent allium, strongly heating. Anti-microbial across all traditions.',
    rasa: ['katu', 'madhura', 'lavana', 'tikta', 'kashaya'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['guru', 'snigdha', 'tikshna'],
    vata_effect: -2,
    pitta_effect: 2,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.9, vasanta: 0.6, grishma: 0.2, varsha: 0.8, sharad: 0.4, hemanta: 0.9 },
    thermal_nature: 'hot',
    flavor: ['pungent'],
    organ_affinity: ['spleen', 'stomach', 'lung'],
    actions: ['warm_middle', 'resolve_toxin', 'resolve_phlegm'],
    element_fit: { wood: 0.3, fire: 0.8, earth: 0.5, metal: 0.6, water: 0.3 },
    glycemic_index: 10,
    bioactive_compounds: [
      { name: 'allicin', amount_per_100g: 2500.0, unit: 'mg' },
      { name: 'alliin', amount_per_100g: 6000.0, unit: 'mg' },
    ],
    contraindications: ['pitta_excess', 'blood_thinners', 'pre_surgery'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'tomato',
    name_sanskrit: null,
    name_chinese: 'xi hong shi',
    category: 'vegetables',
    subcategory: 'fruit_vegetable',
    description: 'Acidic fruit vegetable, rich in lycopene. Heating due to sour taste.',
    rasa: ['amla', 'madhura'],
    virya: 'ushna',
    vipaka: 'amla',
    guna: ['laghu', 'snigdha'],
    vata_effect: 0,
    pitta_effect: 1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.3, vasanta: 0.5, grishma: 0.6, varsha: 0.4, sharad: 0.6, hemanta: 0.4 },
    thermal_nature: 'cool',
    flavor: ['sweet', 'sour'],
    organ_affinity: ['stomach', 'liver'],
    actions: ['generate_fluid', 'clear_heat', 'promote_digestion'],
    element_fit: { wood: 0.6, fire: 0.5, earth: 0.5, metal: 0.3, water: 0.4 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'lycopene', amount_per_100g: 2.6, unit: 'mg' },
      { name: 'beta-carotene', amount_per_100g: 0.4, unit: 'mg' },
    ],
    contraindications: ['nightshade_sensitivity', 'acid_reflux'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'avocado',
    name_sanskrit: null,
    name_chinese: 'niu you guo',
    category: 'fruits',
    subcategory: 'tropical',
    description: 'Rich, fatty fruit high in monounsaturated fats. Heavy and nourishing.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.6, vasanta: 0.4, grishma: 0.5, varsha: 0.5, sharad: 0.6, hemanta: 0.7 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['liver', 'lung'],
    actions: ['nourish_yin', 'moisten_dryness'],
    element_fit: { wood: 0.5, fire: 0.2, earth: 0.6, metal: 0.5, water: 0.6 },
    glycemic_index: 15,
    bioactive_compounds: [
      { name: 'glutathione', amount_per_100g: 17.0, unit: 'mg' },
      { name: 'beta-sitosterol', amount_per_100g: 76.0, unit: 'mg' },
    ],
    contraindications: [],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'lemon',
    name_sanskrit: 'nimbu',
    name_chinese: 'ning meng',
    category: 'fruits',
    subcategory: 'citrus',
    description: 'Sour citrus fruit. Despite acidity, has alkalizing effect post-digestion.',
    rasa: ['amla'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.5, vasanta: 0.7, grishma: 0.5, varsha: 0.7, sharad: 0.6, hemanta: 0.5 },
    thermal_nature: 'cool',
    flavor: ['sour'],
    organ_affinity: ['liver', 'stomach'],
    actions: ['generate_fluid', 'harmonize_stomach', 'resolve_phlegm'],
    element_fit: { wood: 0.7, fire: 0.4, earth: 0.5, metal: 0.5, water: 0.4 },
    glycemic_index: 20,
    bioactive_compounds: [
      { name: 'vitamin_C', amount_per_100g: 53.0, unit: 'mg' },
      { name: 'limonene', amount_per_100g: 170.0, unit: 'mg' },
    ],
    contraindications: ['gastric_ulcer', 'tooth_enamel_erosion'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // BEVERAGES & MISCELLANEOUS
  // =========================================================================
  {
    name: 'green tea',
    name_sanskrit: null,
    name_chinese: 'lu cha',
    category: 'beverages',
    subcategory: 'tea',
    description: 'Unoxidized tea leaves, rich in catechins. Cooling and clarifying.',
    rasa: ['tikta', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.3, vasanta: 0.8, grishma: 0.7, varsha: 0.5, sharad: 0.7, hemanta: 0.3 },
    thermal_nature: 'cool',
    flavor: ['bitter', 'sweet'],
    organ_affinity: ['heart', 'liver', 'stomach'],
    actions: ['clear_heat', 'brighten_eyes', 'promote_urination'],
    element_fit: { wood: 0.7, fire: 0.5, earth: 0.4, metal: 0.5, water: 0.4 },
    glycemic_index: 0,
    bioactive_compounds: [
      { name: 'EGCG', amount_per_100g: 70.0, unit: 'mg' },
      { name: 'L-theanine', amount_per_100g: 25.0, unit: 'mg' },
      { name: 'caffeine', amount_per_100g: 20.0, unit: 'mg' },
    ],
    contraindications: ['caffeine_sensitive', 'iron_deficiency_with_meals'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'coconut water',
    name_sanskrit: 'narikela jala',
    name_chinese: 'ye zi shui',
    category: 'beverages',
    subcategory: 'natural',
    description: 'Natural electrolyte drink from young coconuts. Excellent pitta coolant.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -2,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.3, vasanta: 0.5, grishma: 0.9, varsha: 0.5, sharad: 0.6, hemanta: 0.3 },
    thermal_nature: 'cool',
    flavor: ['sweet'],
    organ_affinity: ['heart', 'kidney', 'stomach'],
    actions: ['generate_fluid', 'clear_heat', 'promote_urination'],
    element_fit: { wood: 0.3, fire: 0.3, earth: 0.5, metal: 0.4, water: 0.8 },
    glycemic_index: 3,
    bioactive_compounds: [
      { name: 'potassium', amount_per_100g: 250.0, unit: 'mg' },
      { name: 'cytokinins', amount_per_100g: 0.01, unit: 'mg' },
    ],
    contraindications: ['hyperkalemia'],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
];
