// Hardcoded seed data for initial herbs.
// Each entry conforms to NewHerb (minus id, created_at, updated_at which have defaults).
// Covers major Ayurvedic, TCM, and crossover herbs.
//
// Dosha effects: -2 strongly reduces, -1 reduces, 0 neutral, +1 aggravates, +2 strongly aggravates

import type { NewHerb } from '../types.js';

type SeedHerb = Omit<NewHerb, 'id' | 'created_at' | 'updated_at'>;

export const HERB_SEEDS: SeedHerb[] = [
  // =========================================================================
  // AYURVEDIC RASAYANA (REJUVENATIVE) HERBS
  // =========================================================================
  {
    name: 'ashwagandha',
    name_sanskrit: 'ashwagandha',
    name_chinese: null,
    category: 'adaptogen',
    subcategory: 'rasayana',
    description:
      'Premier Ayurvedic adaptogen. Builds ojas, calms vata, and strengthens muscles and nerves.',
    rasa: ['tikta', 'kashaya', 'madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -2,
    pitta_effect: 0,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.9, vasanta: 0.5, grishma: 0.4, varsha: 0.6, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'warm',
    flavor: ['bitter', 'astringent', 'sweet'],
    organ_affinity: ['kidney', 'lung'],
    actions: ['tonify_qi', 'tonify_yang', 'calm_shen'],
    element_fit: { wood: 0.3, fire: 0.4, earth: 0.6, metal: 0.5, water: 0.8 },
    herb_actions: ['adaptogenic', 'anti_inflammatory', 'nervine', 'immunomodulatory'],
    contraindications: ['pregnancy', 'hyperthyroidism'],
    dosage_forms: ['powder', 'capsule', 'decoction', 'milk_preparation'],
    pregnancy_safety: 'contraindicated',
    prabhava: 'Balya (strength-giving)',
    is_culinary: false,
    bioactive_compounds: [
      { name: 'withanolides', amount_per_100g: 500.0, unit: 'mg' },
      { name: 'withaferin_A', amount_per_100g: 40.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'shatavari',
    name_sanskrit: 'shatavari',
    name_chinese: 'tian men dong',
    category: 'adaptogen',
    subcategory: 'rasayana',
    description:
      'The "queen of herbs" in Ayurveda. Premier female reproductive tonic. Nourishes all tissues.',
    rasa: ['madhura', 'tikta'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -2,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.5, vasanta: 0.5, grishma: 0.9, varsha: 0.5, sharad: 0.7, hemanta: 0.5 },
    thermal_nature: 'cool',
    flavor: ['sweet', 'bitter'],
    organ_affinity: ['lung', 'kidney', 'stomach'],
    actions: ['tonify_yin', 'generate_fluid', 'moisten_lung'],
    element_fit: { wood: 0.3, fire: 0.2, earth: 0.6, metal: 0.6, water: 0.8 },
    herb_actions: ['galactagogue', 'demulcent', 'adaptogenic', 'antioxidant'],
    contraindications: ['estrogen_sensitive_conditions', 'kidney_disease'],
    dosage_forms: ['powder', 'capsule', 'ghee_preparation', 'decoction'],
    pregnancy_safety: 'safe',
    prabhava: 'Stanya (promotes lactation)',
    is_culinary: false,
    bioactive_compounds: [
      { name: 'shatavarin', amount_per_100g: 800.0, unit: 'mg' },
      { name: 'racemosol', amount_per_100g: 15.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'amalaki',
    name_sanskrit: 'amalaki',
    name_chinese: 'yu gan zi',
    category: 'antioxidant',
    subcategory: 'rasayana',
    description:
      'Indian gooseberry, richest natural source of vitamin C. Part of triphala. Balances all three doshas.',
    rasa: ['amla', 'madhura', 'tikta', 'kashaya', 'katu'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: -1,
    pitta_effect: -2,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.5, vasanta: 0.7, grishma: 0.8, varsha: 0.5, sharad: 0.9, hemanta: 0.5 },
    thermal_nature: 'cool',
    flavor: ['sour', 'sweet', 'bitter', 'astringent', 'pungent'],
    organ_affinity: ['heart', 'lung', 'stomach'],
    actions: ['generate_fluid', 'tonify_yin', 'clear_heat'],
    element_fit: { wood: 0.6, fire: 0.5, earth: 0.6, metal: 0.6, water: 0.5 },
    herb_actions: ['antioxidant', 'immunomodulatory', 'hepatoprotective', 'rejuvenative'],
    contraindications: [],
    dosage_forms: ['powder', 'juice', 'preserve', 'capsule'],
    pregnancy_safety: 'safe',
    prabhava: 'Vayasthapana (anti-aging)',
    is_culinary: true,
    bioactive_compounds: [
      { name: 'vitamin_C', amount_per_100g: 600.0, unit: 'mg' },
      { name: 'gallic_acid', amount_per_100g: 950.0, unit: 'mg' },
      { name: 'ellagic_acid', amount_per_100g: 250.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'brahmi',
    name_sanskrit: 'brahmi',
    name_chinese: null,
    category: 'nootropic',
    subcategory: 'medhya',
    description:
      'Premier brain tonic in Ayurveda. Enhances memory, calms anxiety, supports nerve regeneration.',
    rasa: ['tikta', 'kashaya', 'madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.5, vasanta: 0.6, grishma: 0.7, varsha: 0.5, sharad: 0.7, hemanta: 0.5 },
    thermal_nature: 'cool',
    flavor: ['bitter', 'astringent', 'sweet'],
    organ_affinity: ['heart', 'liver'],
    actions: ['calm_shen', 'clear_heat', 'nourish_heart'],
    element_fit: { wood: 0.5, fire: 0.5, earth: 0.4, metal: 0.4, water: 0.6 },
    herb_actions: ['nootropic', 'anxiolytic', 'neuroprotective', 'antioxidant'],
    contraindications: ['hypothyroidism'],
    dosage_forms: ['powder', 'capsule', 'ghee_preparation', 'syrup'],
    pregnancy_safety: 'caution',
    prabhava: 'Medhya (intellect-promoting)',
    is_culinary: false,
    bioactive_compounds: [
      { name: 'bacosides', amount_per_100g: 1200.0, unit: 'mg' },
      { name: 'bacopasaponins', amount_per_100g: 400.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'guduchi',
    name_sanskrit: 'guduchi',
    name_chinese: null,
    category: 'immunomodulatory',
    subcategory: 'rasayana',
    description:
      'The "divine nectar" (amrita). Powerful immunomodulator that balances all three doshas.',
    rasa: ['tikta', 'kashaya'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.5, vasanta: 0.8, grishma: 0.6, varsha: 0.8, sharad: 0.7, hemanta: 0.5 },
    thermal_nature: 'warm',
    flavor: ['bitter', 'astringent'],
    organ_affinity: ['liver', 'spleen'],
    actions: ['clear_heat', 'resolve_toxin', 'tonify_qi'],
    element_fit: { wood: 0.6, fire: 0.5, earth: 0.5, metal: 0.5, water: 0.4 },
    herb_actions: ['immunomodulatory', 'hepatoprotective', 'antipyretic', 'anti_inflammatory'],
    contraindications: ['autoimmune_conditions'],
    dosage_forms: ['powder', 'decoction', 'tablet', 'satva'],
    pregnancy_safety: 'caution',
    prabhava: 'Amrita (nectar-like quality)',
    is_culinary: false,
    bioactive_compounds: [
      { name: 'tinosporine', amount_per_100g: 300.0, unit: 'mg' },
      { name: 'berberine', amount_per_100g: 80.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // AYURVEDIC DIGESTIVE HERBS
  // =========================================================================
  {
    name: 'triphala',
    name_sanskrit: 'triphala',
    name_chinese: null,
    category: 'digestive',
    subcategory: 'compound',
    description:
      'Classic Ayurvedic formula of three fruits (amalaki, bibhitaki, haritaki). Gentle colon cleanser and rejuvenative.',
    rasa: ['amla', 'tikta', 'kashaya', 'katu', 'madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'ruksha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.6, vasanta: 0.8, grishma: 0.6, varsha: 0.6, sharad: 0.7, hemanta: 0.6 },
    thermal_nature: 'neutral',
    flavor: ['sour', 'bitter', 'astringent', 'pungent', 'sweet'],
    organ_affinity: ['large_intestine', 'stomach', 'liver'],
    actions: ['promote_digestion', 'clear_heat', 'resolve_toxin'],
    element_fit: { wood: 0.6, fire: 0.5, earth: 0.5, metal: 0.7, water: 0.5 },
    herb_actions: ['laxative', 'antioxidant', 'rejuvenative', 'digestive'],
    contraindications: ['diarrhea', 'dysentery'],
    dosage_forms: ['powder', 'tablet', 'decoction', 'capsule'],
    pregnancy_safety: 'contraindicated',
    prabhava: 'Tridoshahara (removes all three doshas)',
    is_culinary: false,
    bioactive_compounds: [
      { name: 'gallic_acid', amount_per_100g: 1500.0, unit: 'mg' },
      { name: 'chebulagic_acid', amount_per_100g: 800.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'trikatu',
    name_sanskrit: 'trikatu',
    name_chinese: null,
    category: 'digestive',
    subcategory: 'compound',
    description:
      'Three pungents formula (ginger, black pepper, long pepper). Ignites agni and burns ama.',
    rasa: ['katu'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha', 'tikshna'],
    vata_effect: -1,
    pitta_effect: 2,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.9, vasanta: 0.7, grishma: 0.1, varsha: 0.8, sharad: 0.3, hemanta: 0.9 },
    thermal_nature: 'hot',
    flavor: ['pungent'],
    organ_affinity: ['stomach', 'lung', 'spleen'],
    actions: ['warm_middle', 'resolve_phlegm', 'promote_digestion'],
    element_fit: { wood: 0.3, fire: 0.9, earth: 0.5, metal: 0.5, water: 0.2 },
    herb_actions: ['digestive', 'carminative', 'bioavailability_enhancer', 'expectorant'],
    contraindications: ['gastric_ulcer', 'pitta_excess', 'acid_reflux'],
    dosage_forms: ['powder', 'tablet', 'capsule'],
    pregnancy_safety: 'caution',
    prabhava: 'Deepana (agni-kindling)',
    is_culinary: true,
    bioactive_compounds: [
      { name: 'piperine', amount_per_100g: 4000.0, unit: 'mg' },
      { name: 'gingerols', amount_per_100g: 1500.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // TCM TONIC HERBS
  // =========================================================================
  {
    name: 'astragalus',
    name_sanskrit: null,
    name_chinese: 'huang qi',
    category: 'adaptogen',
    subcategory: 'qi_tonic',
    description:
      'Premier qi tonic in TCM. Strengthens wei qi (defensive energy), supports immune function.',
    rasa: ['madhura'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.8, vasanta: 0.7, grishma: 0.4, varsha: 0.6, sharad: 0.6, hemanta: 0.8 },
    thermal_nature: 'warm',
    flavor: ['sweet'],
    organ_affinity: ['lung', 'spleen'],
    actions: ['tonify_qi', 'strengthen_wei_qi', 'raise_yang'],
    element_fit: { wood: 0.3, fire: 0.5, earth: 0.8, metal: 0.7, water: 0.4 },
    herb_actions: ['immunomodulatory', 'adaptogenic', 'cardioprotective', 'diuretic'],
    contraindications: ['acute_infection', 'autoimmune_conditions'],
    dosage_forms: ['decoction', 'powder', 'capsule', 'tincture'],
    pregnancy_safety: 'caution',
    prabhava: null,
    is_culinary: true,
    bioactive_compounds: [
      { name: 'astragaloside_IV', amount_per_100g: 25.0, unit: 'mg' },
      { name: 'cycloastragenol', amount_per_100g: 8.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'reishi',
    name_sanskrit: null,
    name_chinese: 'ling zhi',
    category: 'adaptogen',
    subcategory: 'shen_tonic',
    description:
      'The "mushroom of immortality" in TCM. Calms shen, nourishes heart, supports immune modulation.',
    rasa: ['tikta'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.6, vasanta: 0.6, grishma: 0.5, varsha: 0.5, sharad: 0.7, hemanta: 0.6 },
    thermal_nature: 'neutral',
    flavor: ['bitter'],
    organ_affinity: ['heart', 'liver', 'lung'],
    actions: ['calm_shen', 'tonify_qi', 'nourish_heart'],
    element_fit: { wood: 0.6, fire: 0.5, earth: 0.4, metal: 0.5, water: 0.5 },
    herb_actions: ['adaptogenic', 'immunomodulatory', 'hepatoprotective', 'cardioprotective'],
    contraindications: ['blood_thinners', 'pre_surgery'],
    dosage_forms: ['decoction', 'powder', 'capsule', 'tincture'],
    pregnancy_safety: 'caution',
    prabhava: null,
    is_culinary: false,
    bioactive_compounds: [
      { name: 'ganoderic_acid', amount_per_100g: 1500.0, unit: 'mg' },
      { name: 'beta-glucans', amount_per_100g: 4500.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'ginseng',
    name_sanskrit: null,
    name_chinese: 'ren shen',
    category: 'adaptogen',
    subcategory: 'qi_tonic',
    description:
      'The "king of herbs" in TCM. Powerfully tonifies yuan qi, benefits heart and lung.',
    rasa: ['madhura', 'tikta'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['laghu', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.9, vasanta: 0.5, grishma: 0.3, varsha: 0.5, sharad: 0.5, hemanta: 0.9 },
    thermal_nature: 'warm',
    flavor: ['sweet', 'bitter'],
    organ_affinity: ['lung', 'spleen', 'heart'],
    actions: ['tonify_qi', 'generate_fluid', 'calm_shen'],
    element_fit: { wood: 0.3, fire: 0.5, earth: 0.8, metal: 0.6, water: 0.5 },
    herb_actions: ['adaptogenic', 'nootropic', 'anti_fatigue', 'immunomodulatory'],
    contraindications: ['hypertension', 'insomnia', 'acute_infection'],
    dosage_forms: ['decoction', 'powder', 'capsule', 'tincture', 'slice'],
    pregnancy_safety: 'caution',
    prabhava: null,
    is_culinary: true,
    bioactive_compounds: [
      { name: 'ginsenosides', amount_per_100g: 3000.0, unit: 'mg' },
      { name: 'polysaccharides', amount_per_100g: 5000.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'he shou wu',
    name_sanskrit: null,
    name_chinese: 'he shou wu',
    category: 'longevity',
    subcategory: 'blood_tonic',
    description: 'TCM longevity herb. Nourishes liver blood and kidney yin, darkens hair.',
    rasa: ['tikta', 'madhura', 'kashaya'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.7, vasanta: 0.5, grishma: 0.4, varsha: 0.5, sharad: 0.6, hemanta: 0.7 },
    thermal_nature: 'warm',
    flavor: ['bitter', 'sweet', 'astringent'],
    organ_affinity: ['liver', 'kidney'],
    actions: ['tonify_liver', 'tonify_kidney', 'nourish_blood'],
    element_fit: { wood: 0.7, fire: 0.3, earth: 0.4, metal: 0.4, water: 0.8 },
    herb_actions: ['anti_aging', 'hepatoprotective', 'hypolipidemic', 'neuroprotective'],
    contraindications: ['liver_disease', 'diarrhea'],
    dosage_forms: ['decoction', 'powder', 'tablet', 'tincture'],
    pregnancy_safety: 'contraindicated',
    prabhava: null,
    is_culinary: false,
    bioactive_compounds: [
      { name: 'emodin', amount_per_100g: 150.0, unit: 'mg' },
      { name: 'stilbene_glucoside', amount_per_100g: 1200.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'dang gui',
    name_sanskrit: null,
    name_chinese: 'dang gui',
    category: 'blood_tonic',
    subcategory: 'blood_tonic',
    description:
      'TCM "female ginseng." Premier blood tonic, invigorates blood and regulates menses.',
    rasa: ['madhura', 'katu'],
    virya: 'ushna',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: 0,
    kapha_effect: 0,
    ritu_fit: { shishira: 0.7, vasanta: 0.5, grishma: 0.3, varsha: 0.5, sharad: 0.5, hemanta: 0.8 },
    thermal_nature: 'warm',
    flavor: ['sweet', 'pungent'],
    organ_affinity: ['liver', 'heart', 'spleen'],
    actions: ['tonify_blood', 'invigorate_blood', 'moisten_intestines'],
    element_fit: { wood: 0.7, fire: 0.5, earth: 0.5, metal: 0.3, water: 0.5 },
    herb_actions: ['emmenagogue', 'analgesic', 'anti_inflammatory', 'laxative'],
    contraindications: ['menorrhagia', 'diarrhea', 'blood_thinners'],
    dosage_forms: ['decoction', 'powder', 'tincture', 'capsule'],
    pregnancy_safety: 'contraindicated',
    prabhava: null,
    is_culinary: true,
    bioactive_compounds: [
      { name: 'ligustilide', amount_per_100g: 500.0, unit: 'mg' },
      { name: 'ferulic_acid', amount_per_100g: 200.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },

  // =========================================================================
  // CROSSOVER CULINARY HERBS
  // =========================================================================
  {
    name: 'tulsi',
    name_sanskrit: 'tulasi',
    name_chinese: null,
    category: 'adaptogen',
    subcategory: 'medhya',
    description: 'Holy basil, sacred in Ayurveda. Adaptogenic, anti-stress, and immunomodulatory.',
    rasa: ['katu', 'tikta'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha', 'tikshna'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.8, vasanta: 0.7, grishma: 0.3, varsha: 0.9, sharad: 0.5, hemanta: 0.8 },
    thermal_nature: 'warm',
    flavor: ['pungent', 'bitter'],
    organ_affinity: ['lung', 'heart', 'stomach'],
    actions: ['resolve_phlegm', 'promote_digestion', 'clear_heat'],
    element_fit: { wood: 0.4, fire: 0.7, earth: 0.5, metal: 0.6, water: 0.3 },
    herb_actions: ['adaptogenic', 'immunomodulatory', 'expectorant', 'anti_microbial'],
    contraindications: ['blood_thinners'],
    dosage_forms: ['tea', 'powder', 'capsule', 'fresh_leaf'],
    pregnancy_safety: 'caution',
    prabhava: 'Sattvic (purifying)',
    is_culinary: true,
    bioactive_compounds: [
      { name: 'eugenol', amount_per_100g: 4800.0, unit: 'mg' },
      { name: 'ursolic_acid', amount_per_100g: 300.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'neem',
    name_sanskrit: 'nimba',
    name_chinese: null,
    category: 'bitter_tonic',
    subcategory: 'blood_purifier',
    description:
      'Intensely bitter tree used across India. Blood purifier, anti-microbial, and anti-parasitic.',
    rasa: ['tikta', 'kashaya'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha'],
    vata_effect: 1,
    pitta_effect: -2,
    kapha_effect: -2,
    ritu_fit: { shishira: 0.2, vasanta: 0.8, grishma: 0.7, varsha: 0.8, sharad: 0.7, hemanta: 0.2 },
    thermal_nature: 'cool',
    flavor: ['bitter', 'astringent'],
    organ_affinity: ['liver', 'stomach'],
    actions: ['clear_heat', 'resolve_toxin', 'dry_dampness'],
    element_fit: { wood: 0.8, fire: 0.4, earth: 0.3, metal: 0.5, water: 0.3 },
    herb_actions: ['anti_microbial', 'anti_parasitic', 'blood_purifier', 'anti_inflammatory'],
    contraindications: ['vata_excess', 'debility', 'infertility_treatment'],
    dosage_forms: ['tablet', 'powder', 'decoction', 'oil'],
    pregnancy_safety: 'contraindicated',
    prabhava: 'Krumighna (destroys parasites)',
    is_culinary: false,
    bioactive_compounds: [
      { name: 'azadirachtin', amount_per_100g: 300.0, unit: 'mg' },
      { name: 'nimbin', amount_per_100g: 150.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'licorice',
    name_sanskrit: 'yashtimadhu',
    name_chinese: 'gan cao',
    category: 'harmonizer',
    subcategory: 'qi_tonic',
    description:
      'Used in both Ayurveda and TCM as a harmonizer in formulas. Soothes throat and stomach.',
    rasa: ['madhura'],
    virya: 'sheeta',
    vipaka: 'madhura',
    guna: ['guru', 'snigdha'],
    vata_effect: -1,
    pitta_effect: -1,
    kapha_effect: 1,
    ritu_fit: { shishira: 0.6, vasanta: 0.5, grishma: 0.7, varsha: 0.5, sharad: 0.7, hemanta: 0.6 },
    thermal_nature: 'neutral',
    flavor: ['sweet'],
    organ_affinity: ['heart', 'lung', 'spleen', 'stomach'],
    actions: ['tonify_qi', 'moisten_lung', 'harmonize_formula'],
    element_fit: { wood: 0.3, fire: 0.4, earth: 0.8, metal: 0.6, water: 0.4 },
    herb_actions: ['demulcent', 'expectorant', 'anti_inflammatory', 'harmonizer'],
    contraindications: ['hypertension', 'edema', 'hypokalemia'],
    dosage_forms: ['decoction', 'powder', 'capsule', 'lozenge'],
    pregnancy_safety: 'caution',
    prabhava: null,
    is_culinary: true,
    bioactive_compounds: [
      { name: 'glycyrrhizin', amount_per_100g: 6000.0, unit: 'mg' },
      { name: 'liquiritigenin', amount_per_100g: 100.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'peppermint',
    name_sanskrit: 'pudina',
    name_chinese: 'bo he',
    category: 'carminative',
    subcategory: 'digestive',
    description: 'Cooling aromatic herb. Clears liver heat in TCM, relieves digestive discomfort.',
    rasa: ['katu'],
    virya: 'sheeta',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha', 'tikshna'],
    vata_effect: 0,
    pitta_effect: -1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.3, vasanta: 0.7, grishma: 0.9, varsha: 0.5, sharad: 0.7, hemanta: 0.3 },
    thermal_nature: 'cool',
    flavor: ['pungent'],
    organ_affinity: ['lung', 'liver'],
    actions: ['disperse_wind_heat', 'clear_head', 'soothe_liver'],
    element_fit: { wood: 0.7, fire: 0.4, earth: 0.4, metal: 0.6, water: 0.3 },
    herb_actions: ['carminative', 'antispasmodic', 'analgesic', 'diaphoretic'],
    contraindications: ['acid_reflux', 'gallstones'],
    dosage_forms: ['tea', 'tincture', 'essential_oil', 'fresh_leaf'],
    pregnancy_safety: 'safe',
    prabhava: null,
    is_culinary: true,
    bioactive_compounds: [
      { name: 'menthol', amount_per_100g: 5000.0, unit: 'mg' },
      { name: 'rosmarinic_acid', amount_per_100g: 900.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
  {
    name: 'moringa',
    name_sanskrit: 'shigru',
    name_chinese: 'la mu',
    category: 'nutritive',
    subcategory: 'superfood',
    description:
      'Nutrient-dense "drumstick tree." Leaves contain exceptional protein and mineral content.',
    rasa: ['katu', 'tikta'],
    virya: 'ushna',
    vipaka: 'katu',
    guna: ['laghu', 'ruksha', 'tikshna'],
    vata_effect: -1,
    pitta_effect: 1,
    kapha_effect: -1,
    ritu_fit: { shishira: 0.6, vasanta: 0.7, grishma: 0.5, varsha: 0.7, sharad: 0.6, hemanta: 0.6 },
    thermal_nature: 'warm',
    flavor: ['pungent', 'bitter'],
    organ_affinity: ['lung', 'stomach', 'liver'],
    actions: ['promote_digestion', 'resolve_phlegm', 'resolve_toxin'],
    element_fit: { wood: 0.5, fire: 0.5, earth: 0.5, metal: 0.6, water: 0.4 },
    herb_actions: ['nutritive', 'anti_inflammatory', 'galactagogue', 'hypoglycemic'],
    contraindications: ['blood_thinners', 'fertility_treatment'],
    dosage_forms: ['powder', 'capsule', 'fresh_leaf', 'tea'],
    pregnancy_safety: 'caution',
    prabhava: null,
    is_culinary: true,
    bioactive_compounds: [
      { name: 'isothiocyanates', amount_per_100g: 150.0, unit: 'mg' },
      { name: 'quercetin', amount_per_100g: 100.0, unit: 'mg' },
      { name: 'chlorogenic_acid', amount_per_100g: 200.0, unit: 'mg' },
    ],
    seed_source: 'canonical',
    validation_status: 'validated',
  },
];
