/**
 * Mock biomarker extraction results.
 *
 * The real extraction pipeline (text parsing + LLM vision) is stubbed
 * for this split. This module returns realistic fixture biomarkers
 * that the upload handler uses to populate the database immediately.
 */

import type { NormalizedBiomarker } from './canonical-schema.js';

/**
 * Returns a set of fixture biomarkers simulating a LifeLabs CBC + metabolic panel.
 * Includes a mix of normal, low, and high flags to exercise the results UI.
 */
export function getMockBiomarkers(): NormalizedBiomarker[] {
  return [
    {
      canonicalKey: 'glucose_fasting',
      displayName: 'Fasting Glucose',
      value: 5.2,
      unit: 'mmol/L',
      originalUnit: null,
      referenceRangeLow: 3.3,
      referenceRangeHigh: 5.5,
      flag: 'normal',
      loincCode: '1558-6',
      confidence: 0.95,
    },
    {
      canonicalKey: 'hba1c',
      displayName: 'HbA1c',
      value: 5.4,
      unit: '%',
      originalUnit: null,
      referenceRangeLow: 4.0,
      referenceRangeHigh: 5.6,
      flag: 'normal',
      loincCode: '4548-4',
      confidence: 0.92,
    },
    {
      canonicalKey: 'ldl_cholesterol',
      displayName: 'LDL Cholesterol',
      value: 3.8,
      unit: 'mmol/L',
      originalUnit: null,
      referenceRangeLow: null,
      referenceRangeHigh: 3.4,
      flag: 'high',
      loincCode: '2089-1',
      confidence: 0.94,
    },
    {
      canonicalKey: 'hdl_cholesterol',
      displayName: 'HDL Cholesterol',
      value: 1.1,
      unit: 'mmol/L',
      originalUnit: null,
      referenceRangeLow: 1.0,
      referenceRangeHigh: null,
      flag: 'normal',
      loincCode: '2085-9',
      confidence: 0.93,
    },
    {
      canonicalKey: 'total_cholesterol',
      displayName: 'Total Cholesterol',
      value: 5.8,
      unit: 'mmol/L',
      originalUnit: null,
      referenceRangeLow: null,
      referenceRangeHigh: 5.2,
      flag: 'high',
      loincCode: '2093-3',
      confidence: 0.96,
    },
    {
      canonicalKey: 'triglycerides',
      displayName: 'Triglycerides',
      value: 1.4,
      unit: 'mmol/L',
      originalUnit: null,
      referenceRangeLow: null,
      referenceRangeHigh: 1.7,
      flag: 'normal',
      loincCode: '2571-8',
      confidence: 0.91,
    },
    {
      canonicalKey: 'tsh',
      displayName: 'TSH',
      value: 2.1,
      unit: 'mIU/L',
      originalUnit: null,
      referenceRangeLow: 0.4,
      referenceRangeHigh: 4.0,
      flag: 'normal',
      loincCode: '3016-3',
      confidence: 0.89,
    },
    {
      canonicalKey: 'ferritin',
      displayName: 'Ferritin',
      value: 18,
      unit: 'ug/L',
      originalUnit: null,
      referenceRangeLow: 20,
      referenceRangeHigh: 200,
      flag: 'low',
      loincCode: '2276-4',
      confidence: 0.97,
    },
    {
      canonicalKey: 'vitamin_d_25_oh',
      displayName: 'Vitamin D 25-OH',
      value: 42,
      unit: 'nmol/L',
      originalUnit: null,
      referenceRangeLow: 75,
      referenceRangeHigh: 250,
      flag: 'low',
      loincCode: '35365-6',
      confidence: 0.93,
    },
    {
      canonicalKey: 'vitamin_b12',
      displayName: 'Vitamin B12',
      value: 310,
      unit: 'pmol/L',
      originalUnit: null,
      referenceRangeLow: 145,
      referenceRangeHigh: 600,
      flag: 'normal',
      loincCode: '2132-9',
      confidence: 0.88,
    },
    {
      canonicalKey: 'hs_crp',
      displayName: 'hs-CRP',
      value: 3.2,
      unit: 'mg/L',
      originalUnit: null,
      referenceRangeLow: null,
      referenceRangeHigh: 3.0,
      flag: 'high',
      loincCode: '30522-7',
      confidence: 0.9,
    },
    {
      canonicalKey: 'hemoglobin',
      displayName: 'Hemoglobin',
      value: 138,
      unit: 'g/L',
      originalUnit: null,
      referenceRangeLow: 120,
      referenceRangeHigh: 160,
      flag: 'normal',
      loincCode: '718-7',
      confidence: 0.96,
    },
    {
      canonicalKey: 'iron',
      displayName: 'Iron',
      value: 9.5,
      unit: 'umol/L',
      originalUnit: null,
      referenceRangeLow: 9.0,
      referenceRangeHigh: 30.4,
      flag: 'normal',
      loincCode: '14798-3',
      confidence: 0.85,
    },
    {
      canonicalKey: 'wbc',
      displayName: 'White Blood Cells',
      value: 6.2,
      unit: 'x10^9/L',
      originalUnit: null,
      referenceRangeLow: 4.0,
      referenceRangeHigh: 11.0,
      flag: 'normal',
      loincCode: '6690-2',
      confidence: 0.94,
    },
    {
      canonicalKey: 'platelets',
      displayName: 'Platelets',
      value: 245,
      unit: 'x10^9/L',
      originalUnit: null,
      referenceRangeLow: 150,
      referenceRangeHigh: 400,
      flag: 'normal',
      loincCode: '777-3',
      confidence: 0.95,
    },
  ];
}
